import type { PokemonData } from '../types';

export const GEN1: PokemonData[] = [
  {"id": 1, "name": "Bulbasaur", "type": "Grama", "secondType": "Veneno", "BaseTotal": 204, "hp": 45, "atk": 57, "def": 57, "spd": 45, "stage": 1, "nextForm": "Ivysaur", "evoTrigger": 5},
  {"id": 2, "name": "Ivysaur", "type": "Grama", "secondType": "Veneno", "BaseTotal": 263, "hp": 60, "atk": 71, "def": 72, "spd": 60, "stage": 2, "nextForm": "Venusaur", "evoTrigger": 10},
  {"id": 3, "name": "Venusaur", "type": "Grama", "secondType": "Veneno", "BaseTotal": 343, "hp": 80, "atk": 91, "def": 92, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 4, "name": "Charmander", "type": "Fogo", "secondType": "", "BaseTotal": 207, "hp": 39, "atk": 56, "def": 47, "spd": 65, "stage": 1, "nextForm": "Charmeleon", "evoTrigger": 5},
  {"id": 5, "name": "Charmeleon", "type": "Fogo", "secondType": "", "BaseTotal": 272, "hp": 58, "atk": 72, "def": 62, "spd": 80, "stage": 2, "nextForm": "Charizard", "evoTrigger": 10},
  {"id": 6, "name": "Charizard", "type": "Fogo", "secondType": "Voador", "BaseTotal": 357, "hp": 78, "atk": 97, "def": 82, "spd": 100, "stage": 3, "nextForm": null},
  {"id": 7, "name": "Squirtle", "type": "Água", "secondType": "", "BaseTotal": 201, "hp": 44, "atk": 49, "def": 65, "spd": 43, "stage": 1, "nextForm": "Wartortle", "evoTrigger": 5},
  {"id": 8, "name": "Wartortle", "type": "Água", "secondType": "", "BaseTotal": 261, "hp": 59, "atk": 64, "def": 80, "spd": 58, "stage": 2, "nextForm": "Blastoise", "evoTrigger": 10},
  {"id": 9, "name": "Blastoise", "type": "Água", "secondType": "", "BaseTotal": 344, "hp": 79, "atk": 84, "def": 103, "spd": 78, "stage": 3, "nextForm": null},
  {"id": 10, "name": "Caterpie", "type": "Inseto", "secondType": "", "BaseTotal": 143, "hp": 45, "atk": 25, "def": 28, "spd": 45, "stage": 1, "nextForm": "Metapod", "evoTrigger": 5},
  {"id": 11, "name": "Metapod", "type": "Inseto", "secondType": "", "BaseTotal": 143, "hp": 50, "atk": 23, "def": 40, "spd": 30, "stage": 2, "nextForm": "Butterfree", "evoTrigger": 10},
  {"id": 12, "name": "Butterfree", "type": "Inseto", "secondType": "Voador", "BaseTotal": 263, "hp": 60, "atk": 68, "def": 65, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 13, "name": "Weedle", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 143, "hp": 40, "atk": 28, "def": 25, "spd": 50, "stage": 1, "nextForm": "Kakuna", "evoTrigger": 5},
  {"id": 14, "name": "Kakuna", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 143, "hp": 45, "atk": 25, "def": 38, "spd": 35, "stage": 2, "nextForm": "Beedrill", "evoTrigger": 10},
  {"id": 15, "name": "Beedrill", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 268, "hp": 65, "atk": 68, "def": 60, "spd": 75, "stage": 3, "nextForm": null},
  {"id": 16, "name": "Pidgey", "type": "Voador", "secondType": "Normal", "BaseTotal": 174, "hp": 40, "atk": 40, "def": 38, "spd": 56, "stage": 1, "nextForm": "Pidgeotto", "evoTrigger": 5},
  {"id": 17, "name": "Pidgeotto", "type": "Voador", "secondType": "Normal", "BaseTotal": 242, "hp": 63, "atk": 55, "def": 53, "spd": 71, "stage": 2, "nextForm": "Pidgeot", "evoTrigger": 10},
  {"id": 18, "name": "Pidgeot", "type": "Voador", "secondType": "Normal", "BaseTotal": 322, "hp": 83, "atk": 75, "def": 73, "spd": 91, "stage": 3, "nextForm": null},
  {"id": 19, "name": "Rattata", "type": "Normal", "secondType": "", "BaseTotal": 178, "hp": 30, "atk": 41, "def": 35, "spd": 72, "stage": 1, "nextForm": "Raticate", "evoTrigger": 8},
  {"id": 20, "name": "Raticate", "type": "Normal", "secondType": "", "BaseTotal": 283, "hp": 55, "atk": 66, "def": 65, "spd": 97, "stage": 2, "nextForm": null},
  {"id": 21, "name": "Spearow", "type": "Voador", "secondType": "Normal", "BaseTotal": 187, "hp": 40, "atk": 46, "def": 31, "spd": 70, "stage": 1, "nextForm": "Fearow", "evoTrigger": 8},
  {"id": 22, "name": "Fearow", "type": "Voador", "secondType": "Normal", "BaseTotal": 304, "hp": 65, "atk": 76, "def": 63, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 23, "name": "Ekans", "type": "Veneno", "secondType": "", "BaseTotal": 189, "hp": 35, "atk": 50, "def": 49, "spd": 55, "stage": 1, "nextForm": "Arbok", "evoTrigger": 8},
  {"id": 24, "name": "Arbok", "type": "Veneno", "secondType": "", "BaseTotal": 294, "hp": 60, "atk": 80, "def": 74, "spd": 80, "stage": 2, "nextForm": null},
  {"id": 25, "name": "Pikachu", "type": "Elétrico", "secondType": "", "BaseTotal": 223, "hp": 35, "atk": 53, "def": 45, "spd": 90, "stage": 2, "nextForm": "Raichu", "evoTrigger": 10},
  {"id": 26, "name": "Raichu", "type": "Elétrico", "secondType": "", "BaseTotal": 328, "hp": 60, "atk": 90, "def": 68, "spd": 110, "stage": 3, "nextForm": null},
  {"id": 27, "name": "Sandshrew", "type": "Terra", "secondType": "", "BaseTotal": 196, "hp": 50, "atk": 48, "def": 58, "spd": 40, "stage": 1, "nextForm": "Sandslash", "evoTrigger": 8},
  {"id": 28, "name": "Sandslash", "type": "Terra", "secondType": "", "BaseTotal": 296, "hp": 75, "atk": 73, "def": 83, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 29, "name": "Nidoran♀", "type": "Veneno", "secondType": "", "BaseTotal": 186, "hp": 55, "atk": 44, "def": 46, "spd": 41, "stage": 1, "nextForm": "Nidorina", "evoTrigger": 5},
  {"id": 30, "name": "Nidorina", "type": "Veneno", "secondType": "", "BaseTotal": 246, "hp": 70, "atk": 59, "def": 61, "spd": 56, "stage": 2, "nextForm": "Nidoqueen", "evoTrigger": 10},
  {"id": 31, "name": "Nidoqueen", "type": "Veneno", "secondType": "Terra", "BaseTotal": 336, "hp": 90, "atk": 84, "def": 86, "spd": 76, "stage": 3, "nextForm": null},
  {"id": 32, "name": "Nidoran♂", "type": "Veneno", "secondType": "", "BaseTotal": 185, "hp": 46, "atk": 49, "def": 40, "spd": 50, "stage": 1, "nextForm": "Nidorino", "evoTrigger": 5},
  {"id": 33, "name": "Nidorino", "type": "Veneno", "secondType": "", "BaseTotal": 246, "hp": 61, "atk": 64, "def": 56, "spd": 65, "stage": 2, "nextForm": "Nidoking", "evoTrigger": 10},
  {"id": 34, "name": "Nidoking", "type": "Veneno", "secondType": "Terra", "BaseTotal": 336, "hp": 81, "atk": 94, "def": 76, "spd": 85, "stage": 3, "nextForm": null},
  {"id": 35, "name": "Clefairy", "type": "Fada", "secondType": "", "BaseTotal": 215, "hp": 70, "atk": 53, "def": 57, "spd": 35, "stage": 2, "nextForm": "Clefable", "evoTrigger": 10},
  {"id": 36, "name": "Clefable", "type": "Fada", "secondType": "", "BaseTotal": 320, "hp": 95, "atk": 83, "def": 82, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 37, "name": "Vulpix", "type": "Fogo", "secondType": "", "BaseTotal": 202, "hp": 38, "atk": 46, "def": 53, "spd": 65, "stage": 1, "nextForm": "Ninetales", "evoTrigger": 8},
  {"id": 38, "name": "Ninetales", "type": "Fogo", "secondType": "", "BaseTotal": 340, "hp": 73, "atk": 79, "def": 88, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 39, "name": "Jigglypuff", "type": "Fada", "secondType": "Normal", "BaseTotal": 203, "hp": 115, "atk": 45, "def": 23, "spd": 20, "stage": 2, "nextForm": "Wigglytuff", "evoTrigger": 10},
  {"id": 40, "name": "Wigglytuff", "type": "Fada", "secondType": "Normal", "BaseTotal": 311, "hp": 140, "atk": 78, "def": 48, "spd": 45, "stage": 3, "nextForm": null},
  {"id": 41, "name": "Zubat", "type": "Veneno", "secondType": "Voador", "BaseTotal": 171, "hp": 40, "atk": 38, "def": 38, "spd": 55, "stage": 1, "nextForm": "Golbat", "evoTrigger": 5},
  {"id": 42, "name": "Golbat", "type": "Veneno", "secondType": "Voador", "BaseTotal": 311, "hp": 75, "atk": 73, "def": 73, "spd": 90, "stage": 2, "nextForm": "Crobat", "evoTrigger": 10},
  {"id": 43, "name": "Oddish", "type": "Grama", "secondType": "Veneno", "BaseTotal": 198, "hp": 45, "atk": 63, "def": 60, "spd": 30, "stage": 1, "nextForm": "Gloom", "evoTrigger": 5},
  {"id": 44, "name": "Gloom", "type": "Grama", "secondType": "Veneno", "BaseTotal": 248, "hp": 60, "atk": 75, "def": 73, "spd": 40, "stage": 2, "nextForm": "Vileplume", "evoTrigger": 10},
  {"id": 45, "name": "Vileplume", "type": "Grama", "secondType": "Veneno", "BaseTotal": 308, "hp": 75, "atk": 95, "def": 88, "spd": 50, "stage": 3, "nextForm": null},
  {"id": 46, "name": "Paras", "type": "Inseto", "secondType": "Grama", "BaseTotal": 173, "hp": 35, "atk": 58, "def": 55, "spd": 25, "stage": 1, "nextForm": "Parasect", "evoTrigger": 8},
  {"id": 47, "name": "Parasect", "type": "Inseto", "secondType": "Grama", "BaseTotal": 248, "hp": 60, "atk": 78, "def": 80, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 48, "name": "Venonat", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 206, "hp": 60, "atk": 48, "def": 53, "spd": 45, "stage": 1, "nextForm": "Venomoth", "evoTrigger": 8},
  {"id": 49, "name": "Venomoth", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 306, "hp": 70, "atk": 78, "def": 68, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 50, "name": "Diglett", "type": "Terra", "secondType": "", "BaseTotal": 185, "hp": 10, "atk": 45, "def": 35, "spd": 95, "stage": 1, "nextForm": "Dugtrio", "evoTrigger": 8},
  {"id": 51, "name": "Dugtrio", "type": "Terra", "secondType": "", "BaseTotal": 290, "hp": 35, "atk": 75, "def": 60, "spd": 120, "stage": 2, "nextForm": null},
  {"id": 52, "name": "Meowth", "type": "Normal", "secondType": "", "BaseTotal": 211, "hp": 40, "atk": 43, "def": 38, "spd": 90, "stage": 1, "nextForm": "Persian", "evoTrigger": 8},
  {"id": 53, "name": "Persian", "type": "Normal", "secondType": "", "BaseTotal": 311, "hp": 65, "atk": 68, "def": 63, "spd": 115, "stage": 2, "nextForm": null},
  {"id": 54, "name": "Psyduck", "type": "Água", "secondType": "", "BaseTotal": 213, "hp": 50, "atk": 59, "def": 49, "spd": 55, "stage": 1, "nextForm": "Golduck", "evoTrigger": 8},
  {"id": 55, "name": "Golduck", "type": "Água", "secondType": "", "BaseTotal": 333, "hp": 80, "atk": 89, "def": 79, "spd": 85, "stage": 2, "nextForm": null},
  {"id": 56, "name": "Mankey", "type": "Lutador", "secondType": "", "BaseTotal": 208, "hp": 40, "atk": 58, "def": 40, "spd": 70, "stage": 1, "nextForm": "Primeape", "evoTrigger": 5},
  {"id": 57, "name": "Primeape", "type": "Lutador", "secondType": "", "BaseTotal": 308, "hp": 65, "atk": 83, "def": 65, "spd": 95, "stage": 2, "nextForm": "Annihilape", "evoTrigger": 10},
  {"id": 58, "name": "Growlithe", "type": "Fogo", "secondType": "", "BaseTotal": 233, "hp": 55, "atk": 70, "def": 48, "spd": 60, "stage": 1, "nextForm": "Arcanine", "evoTrigger": 8},
  {"id": 59, "name": "Arcanine", "type": "Fogo", "secondType": "", "BaseTotal": 370, "hp": 90, "atk": 105, "def": 80, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 60, "name": "Poliwag", "type": "Água", "secondType": "", "BaseTotal": 215, "hp": 40, "atk": 45, "def": 40, "spd": 90, "stage": 1, "nextForm": "Poliwhirl", "evoTrigger": 5},
  {"id": 61, "name": "Poliwhirl", "type": "Água", "secondType": "", "BaseTotal": 271, "hp": 65, "atk": 58, "def": 58, "spd": 90, "stage": 2, "nextForm": "Poliwrath", "evoTrigger": 10},
  {"id": 62, "name": "Poliwrath", "type": "Água", "secondType": "Lutador", "BaseTotal": 336, "hp": 90, "atk": 83, "def": 93, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 63, "name": "Abra", "type": "Psíquico", "secondType": "", "BaseTotal": 213, "hp": 25, "atk": 63, "def": 35, "spd": 90, "stage": 1, "nextForm": "Kadabra", "evoTrigger": 5},
  {"id": 64, "name": "Kadabra", "type": "Psíquico", "secondType": "", "BaseTotal": 273, "hp": 40, "atk": 78, "def": 50, "spd": 105, "stage": 2, "nextForm": "Alakazam", "evoTrigger": 10},
  {"id": 65, "name": "Alakazam", "type": "Psíquico", "secondType": "", "BaseTotal": 338, "hp": 55, "atk": 93, "def": 70, "spd": 120, "stage": 3, "nextForm": null},
  {"id": 66, "name": "Machop", "type": "Lutador", "secondType": "", "BaseTotal": 206, "hp": 70, "atk": 58, "def": 43, "spd": 35, "stage": 1, "nextForm": "Machoke", "evoTrigger": 5},
  {"id": 67, "name": "Machoke", "type": "Lutador", "secondType": "", "BaseTotal": 265, "hp": 80, "atk": 75, "def": 65, "spd": 45, "stage": 2, "nextForm": "Machamp", "evoTrigger": 10},
  {"id": 68, "name": "Machamp", "type": "Lutador", "secondType": "", "BaseTotal": 326, "hp": 90, "atk": 98, "def": 83, "spd": 55, "stage": 3, "nextForm": null},
  {"id": 69, "name": "Bellsprout", "type": "Grama", "secondType": "Veneno", "BaseTotal": 196, "hp": 50, "atk": 73, "def": 33, "spd": 40, "stage": 1, "nextForm": "Weepinbell", "evoTrigger": 5},
  {"id": 70, "name": "Weepinbell", "type": "Grama", "secondType": "Veneno", "BaseTotal": 256, "hp": 65, "atk": 88, "def": 48, "spd": 55, "stage": 2, "nextForm": "Victreebel", "evoTrigger": 10},
  {"id": 71, "name": "Victreebel", "type": "Grama", "secondType": "Veneno", "BaseTotal": 321, "hp": 80, "atk": 103, "def": 68, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 72, "name": "Tentacool", "type": "Água", "secondType": "Veneno", "BaseTotal": 223, "hp": 40, "atk": 45, "def": 68, "spd": 70, "stage": 1, "nextForm": "Tentacruel", "evoTrigger": 8},
  {"id": 73, "name": "Tentacruel", "type": "Água", "secondType": "Veneno", "BaseTotal": 348, "hp": 80, "atk": 75, "def": 93, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 74, "name": "Geodude", "type": "Pedra", "secondType": "Terra", "BaseTotal": 180, "hp": 40, "atk": 55, "def": 65, "spd": 20, "stage": 1, "nextForm": "Graveler", "evoTrigger": 5},
  {"id": 75, "name": "Graveler", "type": "Pedra", "secondType": "Terra", "BaseTotal": 240, "hp": 55, "atk": 70, "def": 80, "spd": 35, "stage": 2, "nextForm": "Golem", "evoTrigger": 10},
  {"id": 76, "name": "Golem", "type": "Pedra", "secondType": "Terra", "BaseTotal": 312, "hp": 80, "atk": 89, "def": 98, "spd": 45, "stage": 3, "nextForm": null},
  {"id": 77, "name": "Ponyta", "type": "Fogo", "secondType": "", "BaseTotal": 275, "hp": 50, "atk": 75, "def": 60, "spd": 90, "stage": 1, "nextForm": "Rapidash", "evoTrigger": 8},
  {"id": 78, "name": "Rapidash", "type": "Fogo", "secondType": "", "BaseTotal": 335, "hp": 65, "atk": 90, "def": 75, "spd": 105, "stage": 2, "nextForm": null},
  {"id": 79, "name": "Slowpoke", "type": "Água", "secondType": "Psíquico", "BaseTotal": 211, "hp": 90, "atk": 53, "def": 53, "spd": 15, "stage": 1, "nextForm": "Slowbro", "evoTrigger": 8},
  {"id": 80, "name": "Slowbro", "type": "Água", "secondType": "Psíquico", "BaseTotal": 308, "hp": 95, "atk": 88, "def": 95, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 81, "name": "Magnemite", "type": "Elétrico", "secondType": "Aço", "BaseTotal": 198, "hp": 25, "atk": 65, "def": 63, "spd": 45, "stage": 1, "nextForm": "Magneton", "evoTrigger": 5},
  {"id": 82, "name": "Magneton", "type": "Elétrico", "secondType": "Aço", "BaseTotal": 293, "hp": 50, "atk": 90, "def": 83, "spd": 70, "stage": 2, "nextForm": "Magnezone", "evoTrigger": 10},
  {"id": 83, "name": "Farfetch'd", "type": "Normal", "secondType": "Voador", "BaseTotal": 242, "hp": 52, "atk": 77, "def": 58, "spd": 55, "stage": 1, "nextForm": "Sirfetch'd", "evoTrigger": 8},
  {"id": 84, "name": "Doduo", "type": "Voador", "secondType": "Normal", "BaseTotal": 210, "hp": 35, "atk": 60, "def": 40, "spd": 75, "stage": 1, "nextForm": "Dodrio", "evoTrigger": 8},
  {"id": 85, "name": "Dodrio", "type": "Voador", "secondType": "Normal", "BaseTotal": 310, "hp": 60, "atk": 85, "def": 65, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 86, "name": "Seel", "type": "Água", "secondType": "", "BaseTotal": 218, "hp": 65, "atk": 45, "def": 63, "spd": 45, "stage": 1, "nextForm": "Dewgong", "evoTrigger": 8},
  {"id": 87, "name": "Dewgong", "type": "Gelo", "secondType": "Água", "BaseTotal": 318, "hp": 90, "atk": 70, "def": 88, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 88, "name": "Grimer", "type": "Veneno", "secondType": "", "BaseTotal": 215, "hp": 80, "atk": 60, "def": 50, "spd": 25, "stage": 1, "nextForm": "Muk", "evoTrigger": 8},
  {"id": 89, "name": "Muk", "type": "Veneno", "secondType": "", "BaseTotal": 328, "hp": 105, "atk": 85, "def": 88, "spd": 50, "stage": 2, "nextForm": null},
  {"id": 90, "name": "Shellder", "type": "Água", "secondType": "", "BaseTotal": 188, "hp": 30, "atk": 55, "def": 63, "spd": 40, "stage": 1, "nextForm": "Cloyster", "evoTrigger": 8},
  {"id": 91, "name": "Cloyster", "type": "Gelo", "secondType": "Água", "BaseTotal": 323, "hp": 50, "atk": 90, "def": 113, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 92, "name": "Gastly", "type": "Fantasma", "secondType": "Veneno", "BaseTotal": 211, "hp": 30, "atk": 68, "def": 33, "spd": 80, "stage": 1, "nextForm": "Haunter", "evoTrigger": 5},
  {"id": 93, "name": "Haunter", "type": "Fantasma", "secondType": "Veneno", "BaseTotal": 273, "hp": 45, "atk": 83, "def": 50, "spd": 95, "stage": 2, "nextForm": "Gengar", "evoTrigger": 10},
  {"id": 94, "name": "Gengar", "type": "Fantasma", "secondType": "Veneno", "BaseTotal": 336, "hp": 60, "atk": 98, "def": 68, "spd": 110, "stage": 3, "nextForm": null},
  {"id": 95, "name": "Onix", "type": "Pedra", "secondType": "Terra", "BaseTotal": 246, "hp": 35, "atk": 38, "def": 103, "spd": 70, "stage": 1, "nextForm": "Steelix", "evoTrigger": 8},
  {"id": 96, "name": "Drowzee", "type": "Psíquico", "secondType": "", "BaseTotal": 216, "hp": 60, "atk": 46, "def": 68, "spd": 42, "stage": 1, "nextForm": "Hypno", "evoTrigger": 8},
  {"id": 97, "name": "Hypno", "type": "Psíquico", "secondType": "", "BaseTotal": 318, "hp": 85, "atk": 73, "def": 93, "spd": 67, "stage": 2, "nextForm": null},
  {"id": 98, "name": "Krabby", "type": "Água", "secondType": "", "BaseTotal": 201, "hp": 30, "atk": 65, "def": 56, "spd": 50, "stage": 1, "nextForm": "Kingler", "evoTrigger": 8},
  {"id": 99, "name": "Kingler", "type": "Água", "secondType": "", "BaseTotal": 303, "hp": 55, "atk": 90, "def": 83, "spd": 75, "stage": 2, "nextForm": null},
  {"id": 100, "name": "Voltorb", "type": "Elétrico", "secondType": "", "BaseTotal": 236, "hp": 40, "atk": 43, "def": 53, "spd": 100, "stage": 1, "nextForm": "Electrode", "evoTrigger": 8},
  {"id": 101, "name": "Electrode", "type": "Elétrico", "secondType": "", "BaseTotal": 340, "hp": 60, "atk": 65, "def": 75, "spd": 140, "stage": 2, "nextForm": null},
  {"id": 102, "name": "Exeggcute", "type": "Grama", "secondType": "Psíquico", "BaseTotal": 213, "hp": 60, "atk": 50, "def": 63, "spd": 40, "stage": 1, "nextForm": "Exeggutor", "evoTrigger": 8},
  {"id": 103, "name": "Exeggutor", "type": "Grama", "secondType": "Psíquico", "BaseTotal": 340, "hp": 95, "atk": 110, "def": 80, "spd": 55, "stage": 2, "nextForm": null},
  {"id": 104, "name": "Cubone", "type": "Terra", "secondType": "", "BaseTotal": 203, "hp": 50, "atk": 45, "def": 73, "spd": 35, "stage": 1, "nextForm": "Marowak", "evoTrigger": 8},
  {"id": 105, "name": "Marowak", "type": "Terra", "secondType": "", "BaseTotal": 265, "hp": 60, "atk": 65, "def": 95, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 106, "name": "Hitmonlee", "type": "Lutador", "secondType": "", "BaseTotal": 297, "hp": 50, "atk": 78, "def": 82, "spd": 87, "stage": 1, "nextForm": null},
  {"id": 107, "name": "Hitmonchan", "type": "Lutador", "secondType": "", "BaseTotal": 291, "hp": 50, "atk": 70, "def": 95, "spd": 76, "stage": 1, "nextForm": null},
  {"id": 108, "name": "Lickitung", "type": "Normal", "secondType": "", "BaseTotal": 253, "hp": 90, "atk": 58, "def": 75, "spd": 30, "stage": 1, "nextForm": "Lickilicky", "evoTrigger": 8},
  {"id": 109, "name": "Koffing", "type": "Veneno", "secondType": "", "BaseTotal": 208, "hp": 40, "atk": 63, "def": 70, "spd": 35, "stage": 1, "nextForm": "Weezing", "evoTrigger": 8},
  {"id": 110, "name": "Weezing", "type": "Veneno", "secondType": "", "BaseTotal": 308, "hp": 65, "atk": 88, "def": 95, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 111, "name": "Rhyhorn", "type": "Terra", "secondType": "Pedra", "BaseTotal": 224, "hp": 80, "atk": 56, "def": 63, "spd": 25, "stage": 1, "nextForm": "Rhydon", "evoTrigger": 5},
  {"id": 112, "name": "Rhydon", "type": "Terra", "secondType": "Pedra", "BaseTotal": 316, "hp": 105, "atk": 88, "def": 83, "spd": 40, "stage": 2, "nextForm": "Rhyperior", "evoTrigger": 10},
  {"id": 113, "name": "Chansey", "type": "Normal", "secondType": "", "BaseTotal": 375, "hp": 250, "atk": 20, "def": 55, "spd": 50, "stage": 2, "nextForm": "Blissey", "evoTrigger": 10},
  {"id": 114, "name": "Tangela", "type": "Grama", "secondType": "", "BaseTotal": 281, "hp": 65, "atk": 78, "def": 78, "spd": 60, "stage": 1, "nextForm": "Tangrowth", "evoTrigger": 8},
  {"id": 115, "name": "Kangaskhan", "type": "Normal", "secondType": "", "BaseTotal": 343, "hp": 105, "atk": 68, "def": 80, "spd": 90, "stage": 1, "nextForm": null},
  {"id": 116, "name": "Horsea", "type": "Água", "secondType": "", "BaseTotal": 193, "hp": 30, "atk": 55, "def": 48, "spd": 60, "stage": 1, "nextForm": "Seadra", "evoTrigger": 5},
  {"id": 117, "name": "Seadra", "type": "Água", "secondType": "", "BaseTotal": 290, "hp": 55, "atk": 80, "def": 70, "spd": 85, "stage": 2, "nextForm": "Kingdra", "evoTrigger": 10},
  {"id": 118, "name": "Goldeen", "type": "Água", "secondType": "", "BaseTotal": 214, "hp": 45, "atk": 51, "def": 55, "spd": 63, "stage": 1, "nextForm": "Seaking", "evoTrigger": 8},
  {"id": 119, "name": "Seaking", "type": "Água", "secondType": "", "BaseTotal": 300, "hp": 80, "atk": 79, "def": 73, "spd": 68, "stage": 2, "nextForm": null},
  {"id": 120, "name": "Staryu", "type": "Água", "secondType": "", "BaseTotal": 228, "hp": 30, "atk": 58, "def": 55, "spd": 85, "stage": 1, "nextForm": "Starmie", "evoTrigger": 8},
  {"id": 121, "name": "Starmie", "type": "Água", "secondType": "Psíquico", "BaseTotal": 348, "hp": 60, "atk": 88, "def": 85, "spd": 115, "stage": 2, "nextForm": null},
  {"id": 122, "name": "Mr. Mime", "type": "Fada", "secondType": "Psíquico", "BaseTotal": 296, "hp": 40, "atk": 73, "def": 93, "spd": 90, "stage": 2, "nextForm": "Mr. Rime", "evoTrigger": 10},
  {"id": 123, "name": "Scyther", "type": "Inseto", "secondType": "Voador", "BaseTotal": 338, "hp": 70, "atk": 83, "def": 80, "spd": 105, "stage": 1, "nextForm": "Scizor", "evoTrigger": 8},
  {"id": 124, "name": "Jynx", "type": "Gelo", "secondType": "Psíquico", "BaseTotal": 308, "hp": 65, "atk": 83, "def": 65, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 125, "name": "Electabuzz", "type": "Elétrico", "secondType": "", "BaseTotal": 330, "hp": 65, "atk": 89, "def": 71, "spd": 105, "stage": 2, "nextForm": "Electivire", "evoTrigger": 10},
  {"id": 126, "name": "Magmar", "type": "Fogo", "secondType": "", "BaseTotal": 327, "hp": 65, "atk": 98, "def": 71, "spd": 93, "stage": 2, "nextForm": "Magmortar", "evoTrigger": 10},
  {"id": 127, "name": "Pinsir", "type": "Inseto", "secondType": "", "BaseTotal": 325, "hp": 65, "atk": 90, "def": 85, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 128, "name": "Tauros", "type": "Normal", "secondType": "", "BaseTotal": 338, "hp": 75, "atk": 70, "def": 83, "spd": 110, "stage": 1, "nextForm": null},
  {"id": 129, "name": "Magikarp", "type": "Água", "secondType": "", "BaseTotal": 151, "hp": 20, "atk": 13, "def": 38, "spd": 80, "stage": 1, "nextForm": "Gyarados", "evoTrigger": 8},
  {"id": 130, "name": "Gyarados", "type": "Água", "secondType": "Voador", "BaseTotal": 359, "hp": 95, "atk": 93, "def": 90, "spd": 81, "stage": 2, "nextForm": null},
  {"id": 131, "name": "Lapras", "type": "Gelo", "secondType": "Água", "BaseTotal": 363, "hp": 130, "atk": 85, "def": 88, "spd": 60, "stage": 1, "nextForm": null},
  {"id": 132, "name": "Ditto", "type": "Normal", "secondType": "", "BaseTotal": 192, "hp": 48, "atk": 48, "def": 48, "spd": 48, "stage": 1, "nextForm": null},
  {"id": 133, "name": "Eevee", "type": "Normal", "secondType": "", "BaseTotal": 218, "hp": 55, "atk": 50, "def": 58, "spd": 55, "stage": 1, "nextForm": "Vaporeon", "evoTrigger": 8},
  {"id": 134, "name": "Vaporeon", "type": "Água", "secondType": "", "BaseTotal": 361, "hp": 130, "atk": 88, "def": 78, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 135, "name": "Jolteon", "type": "Elétrico", "secondType": "", "BaseTotal": 361, "hp": 65, "atk": 88, "def": 78, "spd": 130, "stage": 2, "nextForm": null},
  {"id": 136, "name": "Flareon", "type": "Fogo", "secondType": "", "BaseTotal": 328, "hp": 65, "atk": 113, "def": 85, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 137, "name": "Porygon", "type": "Normal", "secondType": "", "BaseTotal": 251, "hp": 65, "atk": 73, "def": 73, "spd": 40, "stage": 1, "nextForm": "Porygon2", "evoTrigger": 5},
  {"id": 138, "name": "Omanyte", "type": "Pedra", "secondType": "Água", "BaseTotal": 213, "hp": 35, "atk": 65, "def": 78, "spd": 35, "stage": 1, "nextForm": "Omastar", "evoTrigger": 8},
  {"id": 139, "name": "Omastar", "type": "Pedra", "secondType": "Água", "BaseTotal": 311, "hp": 70, "atk": 88, "def": 98, "spd": 55, "stage": 2, "nextForm": null},
  {"id": 140, "name": "Kabuto", "type": "Pedra", "secondType": "Água", "BaseTotal": 221, "hp": 30, "atk": 68, "def": 68, "spd": 55, "stage": 1, "nextForm": "Kabutops", "evoTrigger": 8},
  {"id": 141, "name": "Kabutops", "type": "Pedra", "secondType": "Água", "BaseTotal": 318, "hp": 60, "atk": 90, "def": 88, "spd": 80, "stage": 2, "nextForm": null},
  {"id": 142, "name": "Aerodactyl", "type": "Pedra", "secondType": "Voador", "BaseTotal": 363, "hp": 80, "atk": 83, "def": 70, "spd": 130, "stage": 1, "nextForm": null},
  {"id": 143, "name": "Snorlax", "type": "Normal", "secondType": "", "BaseTotal": 366, "hp": 160, "atk": 88, "def": 88, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 144, "name": "Articuno", "type": "Gelo", "secondType": "Voador", "BaseTotal": 378, "hp": 90, "atk": 90, "def": 113, "spd": 85, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 145, "name": "Zapdos", "type": "Elétrico", "secondType": "Voador", "BaseTotal": 386, "hp": 90, "atk": 108, "def": 88, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 146, "name": "Moltres", "type": "Fogo", "secondType": "Voador", "BaseTotal": 381, "hp": 90, "atk": 113, "def": 88, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 147, "name": "Dratini", "type": "Dragão", "secondType": "", "BaseTotal": 196, "hp": 41, "atk": 57, "def": 48, "spd": 50, "stage": 1, "nextForm": "Dragonair", "evoTrigger": 5},
  {"id": 148, "name": "Dragonair", "type": "Dragão", "secondType": "", "BaseTotal": 276, "hp": 61, "atk": 77, "def": 68, "spd": 70, "stage": 2, "nextForm": "Dragonite", "evoTrigger": 10},
  {"id": 149, "name": "Dragonite", "type": "Dragão", "secondType": "Voador", "BaseTotal": 386, "hp": 91, "atk": 117, "def": 98, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 150, "name": "Mewtwo", "type": "Psíquico", "secondType": "", "BaseTotal": 458, "hp": 106, "atk": 132, "def": 90, "spd": 130, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 151, "name": "Mew", "type": "Psíquico", "secondType": "", "BaseTotal": 400, "hp": 100, "atk": 100, "def": 100, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true}
];
