import type { PokemonData } from '../types';

export const GEN2: PokemonData[] = [
  {"id": 152, "name": "Chikorita", "type": "Grama", "secondType": "", "BaseTotal": 204, "hp": 45, "atk": 49, "def": 65, "spd": 45, "stage": 1, "nextForm": "Bayleef", "evoTrigger": 5},
  {"id": 153, "name": "Bayleef", "type": "Grama", "secondType": "", "BaseTotal": 262, "hp": 60, "atk": 62, "def": 80, "spd": 60, "stage": 2, "nextForm": "Meganium", "evoTrigger": 10},
  {"id": 154, "name": "Meganium", "type": "Grama", "secondType": "", "BaseTotal": 342, "hp": 80, "atk": 82, "def": 100, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 155, "name": "Cyndaquil", "type": "Fogo", "secondType": "", "BaseTotal": 206, "hp": 39, "atk": 56, "def": 46, "spd": 65, "stage": 1, "nextForm": "Quilava", "evoTrigger": 5},
  {"id": 156, "name": "Quilava", "type": "Fogo", "secondType": "", "BaseTotal": 272, "hp": 58, "atk": 72, "def": 62, "spd": 80, "stage": 2, "nextForm": "Typhlosion", "evoTrigger": 10},
  {"id": 157, "name": "Typhlosion", "type": "Fogo", "secondType": "", "BaseTotal": 356, "hp": 78, "atk": 96, "def": 82, "spd": 100, "stage": 3, "nextForm": null},
  {"id": 158, "name": "Totodile", "type": "Água", "secondType": "", "BaseTotal": 203, "hp": 50, "atk": 54, "def": 56, "spd": 43, "stage": 1, "nextForm": "Croconaw", "evoTrigger": 5},
  {"id": 159, "name": "Croconaw", "type": "Água", "secondType": "", "BaseTotal": 265, "hp": 65, "atk": 70, "def": 72, "spd": 58, "stage": 2, "nextForm": "Feraligatr", "evoTrigger": 10},
  {"id": 160, "name": "Feraligatr", "type": "Água", "secondType": "", "BaseTotal": 347, "hp": 85, "atk": 92, "def": 92, "spd": 78, "stage": 3, "nextForm": null},
  {"id": 161, "name": "Sentret", "type": "Normal", "secondType": "", "BaseTotal": 135, "hp": 35, "atk": 40, "def": 40, "spd": 20, "stage": 1, "nextForm": "Furret", "evoTrigger": 8},
  {"id": 162, "name": "Furret", "type": "Normal", "secondType": "", "BaseTotal": 295, "hp": 85, "atk": 60, "def": 60, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 163, "name": "Hoothoot", "type": "Normal", "secondType": "Voador", "BaseTotal": 186, "hp": 60, "atk": 33, "def": 43, "spd": 50, "stage": 1, "nextForm": "Noctowl", "evoTrigger": 8},
  {"id": 164, "name": "Noctowl", "type": "Normal", "secondType": "Voador", "BaseTotal": 306, "hp": 100, "atk": 63, "def": 73, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 165, "name": "Ledyba", "type": "Inseto", "secondType": "Voador", "BaseTotal": 180, "hp": 40, "atk": 30, "def": 55, "spd": 55, "stage": 1, "nextForm": "Ledian", "evoTrigger": 8},
  {"id": 166, "name": "Ledian", "type": "Inseto", "secondType": "Voador", "BaseTotal": 265, "hp": 55, "atk": 45, "def": 80, "spd": 85, "stage": 2, "nextForm": null},
  {"id": 167, "name": "Spinarak", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 160, "hp": 40, "atk": 50, "def": 40, "spd": 30, "stage": 1, "nextForm": "Ariados", "evoTrigger": 8},
  {"id": 168, "name": "Ariados", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 255, "hp": 70, "atk": 75, "def": 70, "spd": 40, "stage": 2, "nextForm": null},
  {"id": 169, "name": "Crobat", "type": "Veneno", "secondType": "Voador", "BaseTotal": 375, "hp": 85, "atk": 80, "def": 80, "spd": 130, "stage": 3, "nextForm": null},
  {"id": 170, "name": "Chinchou", "type": "Água", "secondType": "Elétrico", "BaseTotal": 236, "hp": 75, "atk": 47, "def": 47, "spd": 67, "stage": 1, "nextForm": "Lanturn", "evoTrigger": 8},
  {"id": 171, "name": "Lanturn", "type": "Água", "secondType": "Elétrico", "BaseTotal": 326, "hp": 125, "atk": 67, "def": 67, "spd": 67, "stage": 2, "nextForm": null},
  {"id": 172, "name": "Pichu", "type": "Elétrico", "secondType": "", "BaseTotal": 143, "hp": 20, "atk": 38, "def": 25, "spd": 60, "stage": 1, "nextForm": "Pikachu", "evoTrigger": 5},
  {"id": 173, "name": "Cleffa", "type": "Fada", "secondType": "", "BaseTotal": 142, "hp": 50, "atk": 35, "def": 42, "spd": 15, "stage": 1, "nextForm": "Clefairy", "evoTrigger": 5},
  {"id": 174, "name": "Igglybuff", "type": "Normal", "secondType": "Fada", "BaseTotal": 158, "hp": 90, "atk": 35, "def": 18, "spd": 15, "stage": 1, "nextForm": "Jigglypuff", "evoTrigger": 5},
  {"id": 175, "name": "Togepi", "type": "Fada", "secondType": "", "BaseTotal": 150, "hp": 35, "atk": 30, "def": 65, "spd": 20, "stage": 1, "nextForm": "Togetic", "evoTrigger": 5},
  {"id": 176, "name": "Togetic", "type": "Fada", "secondType": "Voador", "BaseTotal": 250, "hp": 55, "atk": 60, "def": 95, "spd": 40, "stage": 2, "nextForm": "Togekiss", "evoTrigger": 10},
  {"id": 177, "name": "Natu", "type": "Psíquico", "secondType": "Voador", "BaseTotal": 215, "hp": 40, "atk": 60, "def": 45, "spd": 70, "stage": 1, "nextForm": "Xatu", "evoTrigger": 8},
  {"id": 178, "name": "Xatu", "type": "Psíquico", "secondType": "Voador", "BaseTotal": 315, "hp": 65, "atk": 85, "def": 70, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 179, "name": "Mareep", "type": "Elétrico", "secondType": "", "BaseTotal": 184, "hp": 55, "atk": 52, "def": 42, "spd": 35, "stage": 1, "nextForm": "Flaaffy", "evoTrigger": 5},
  {"id": 180, "name": "Flaaffy", "type": "Elétrico", "secondType": "", "BaseTotal": 241, "hp": 70, "atk": 68, "def": 58, "spd": 45, "stage": 2, "nextForm": "Ampharos", "evoTrigger": 10},
  {"id": 181, "name": "Ampharos", "type": "Elétrico", "secondType": "", "BaseTotal": 328, "hp": 90, "atk": 95, "def": 88, "spd": 55, "stage": 3, "nextForm": null},
  {"id": 182, "name": "Bellossom", "type": "Grama", "secondType": "", "BaseTotal": 308, "hp": 75, "atk": 85, "def": 98, "spd": 50, "stage": 3, "nextForm": null},
  {"id": 183, "name": "Marill", "type": "Água", "secondType": "Fada", "BaseTotal": 180, "hp": 70, "atk": 20, "def": 50, "spd": 40, "stage": 2, "nextForm": "Azumarill", "evoTrigger": 10},
  {"id": 184, "name": "Azumarill", "type": "Água", "secondType": "Fada", "BaseTotal": 285, "hp": 100, "atk": 55, "def": 80, "spd": 50, "stage": 3, "nextForm": null},
  {"id": 185, "name": "Sudowoodo", "type": "Pedra", "secondType": "", "BaseTotal": 255, "hp": 70, "atk": 65, "def": 90, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 186, "name": "Politoed", "type": "Água", "secondType": "", "BaseTotal": 330, "hp": 90, "atk": 82, "def": 88, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 187, "name": "Hoppip", "type": "Grama", "secondType": "Voador", "BaseTotal": 168, "hp": 35, "atk": 35, "def": 48, "spd": 50, "stage": 1, "nextForm": "Skiploom", "evoTrigger": 5},
  {"id": 188, "name": "Skiploom", "type": "Grama", "secondType": "Voador", "BaseTotal": 238, "hp": 55, "atk": 45, "def": 58, "spd": 80, "stage": 2, "nextForm": "Jumpluff", "evoTrigger": 10},
  {"id": 189, "name": "Jumpluff", "type": "Grama", "secondType": "Voador", "BaseTotal": 322, "hp": 75, "atk": 55, "def": 82, "spd": 110, "stage": 3, "nextForm": null},
  {"id": 190, "name": "Aipom", "type": "Normal", "secondType": "", "BaseTotal": 250, "hp": 55, "atk": 55, "def": 55, "spd": 85, "stage": 1, "nextForm": "Ambipom", "evoTrigger": 8},
  {"id": 191, "name": "Sunkern", "type": "Grama", "secondType": "", "BaseTotal": 120, "hp": 30, "atk": 30, "def": 30, "spd": 30, "stage": 1, "nextForm": "Sunflora", "evoTrigger": 8},
  {"id": 192, "name": "Sunflora", "type": "Grama", "secondType": "", "BaseTotal": 265, "hp": 75, "atk": 90, "def": 70, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 193, "name": "Yanma", "type": "Inseto", "secondType": "Voador", "BaseTotal": 275, "hp": 65, "atk": 70, "def": 45, "spd": 95, "stage": 1, "nextForm": "Yanmega", "evoTrigger": 8},
  {"id": 194, "name": "Wooper", "type": "Água", "secondType": "Terra", "BaseTotal": 140, "hp": 55, "atk": 35, "def": 35, "spd": 15, "stage": 1, "nextForm": "Quagsire", "evoTrigger": 8},
  {"id": 195, "name": "Quagsire", "type": "Água", "secondType": "Terra", "BaseTotal": 280, "hp": 95, "atk": 75, "def": 75, "spd": 35, "stage": 2, "nextForm": null},
  {"id": 196, "name": "Espeon", "type": "Psíquico", "secondType": "", "BaseTotal": 351, "hp": 65, "atk": 98, "def": 78, "spd": 110, "stage": 2, "nextForm": null},
  {"id": 197, "name": "Umbreon", "type": "Noturno", "secondType": "", "BaseTotal": 342, "hp": 95, "atk": 62, "def": 120, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 198, "name": "Murkrow", "type": "Noturno", "secondType": "Voador", "BaseTotal": 278, "hp": 60, "atk": 85, "def": 42, "spd": 91, "stage": 1, "nextForm": "Honchkrow", "evoTrigger": 8},
  {"id": 199, "name": "Slowking", "type": "Água", "secondType": "Psíquico", "BaseTotal": 308, "hp": 95, "atk": 88, "def": 95, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 200, "name": "Misdreavus", "type": "Fantasma", "secondType": "", "BaseTotal": 289, "hp": 60, "atk": 72, "def": 72, "spd": 85, "stage": 1, "nextForm": "Mismagius", "evoTrigger": 8},
  {"id": 201, "name": "Unown", "type": "Psíquico", "secondType": "", "BaseTotal": 216, "hp": 48, "atk": 72, "def": 48, "spd": 48, "stage": 1, "nextForm": null},
  {"id": 202, "name": "Wobbuffet", "type": "Psíquico", "secondType": "", "BaseTotal": 314, "hp": 190, "atk": 33, "def": 58, "spd": 33, "stage": 2, "nextForm": null},
  {"id": 203, "name": "Girafarig", "type": "Normal", "secondType": "Psíquico", "BaseTotal": 305, "hp": 70, "atk": 85, "def": 65, "spd": 85, "stage": 1, "nextForm": "Farigiraf", "evoTrigger": 8},
  {"id": 204, "name": "Pineco", "type": "Inseto", "secondType": "", "BaseTotal": 177, "hp": 50, "atk": 50, "def": 62, "spd": 15, "stage": 1, "nextForm": "Forretress", "evoTrigger": 8},
  {"id": 205, "name": "Forretress", "type": "Inseto", "secondType": "Aço", "BaseTotal": 290, "hp": 75, "atk": 75, "def": 100, "spd": 40, "stage": 2, "nextForm": null},
  {"id": 206, "name": "Dunsparce", "type": "Normal", "secondType": "", "BaseTotal": 281, "hp": 100, "atk": 68, "def": 68, "spd": 45, "stage": 1, "nextForm": "Dudunsparce", "evoTrigger": 8},
  {"id": 207, "name": "Gligar", "type": "Terra", "secondType": "Voador", "BaseTotal": 290, "hp": 65, "atk": 55, "def": 85, "spd": 85, "stage": 1, "nextForm": "Gliscor", "evoTrigger": 8},
  {"id": 208, "name": "Steelix", "type": "Aço", "secondType": "Terra", "BaseTotal": 307, "hp": 75, "atk": 70, "def": 132, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 209, "name": "Snubbull", "type": "Fada", "secondType": "", "BaseTotal": 195, "hp": 60, "atk": 60, "def": 45, "spd": 30, "stage": 1, "nextForm": "Granbull", "evoTrigger": 8},
  {"id": 210, "name": "Granbull", "type": "Fada", "secondType": "", "BaseTotal": 293, "hp": 90, "atk": 90, "def": 68, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 211, "name": "Qwilfish", "type": "Água", "secondType": "Veneno", "BaseTotal": 295, "hp": 65, "atk": 75, "def": 70, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 212, "name": "Scizor", "type": "Inseto", "secondType": "Aço", "BaseTotal": 317, "hp": 70, "atk": 92, "def": 90, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 213, "name": "Shuckle", "type": "Inseto", "secondType": "Pedra", "BaseTotal": 265, "hp": 20, "atk": 10, "def": 230, "spd": 5, "stage": 1, "nextForm": null},
  {"id": 214, "name": "Heracross", "type": "Inseto", "secondType": "Lutador", "BaseTotal": 332, "hp": 80, "atk": 82, "def": 85, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 215, "name": "Sneasel", "type": "Noturno", "secondType": "Gelo", "BaseTotal": 300, "hp": 55, "atk": 65, "def": 65, "spd": 115, "stage": 1, "nextForm": "Weavile", "evoTrigger": 8},
  {"id": 216, "name": "Teddiursa", "type": "Normal", "secondType": "", "BaseTotal": 215, "hp": 60, "atk": 65, "def": 50, "spd": 40, "stage": 1, "nextForm": "Ursaring", "evoTrigger": 8},
  {"id": 217, "name": "Ursaring", "type": "Normal", "secondType": "", "BaseTotal": 322, "hp": 90, "atk": 102, "def": 75, "spd": 55, "stage": 2, "nextForm": null},
  {"id": 218, "name": "Slugma", "type": "Fogo", "secondType": "", "BaseTotal": 155, "hp": 40, "atk": 55, "def": 40, "spd": 20, "stage": 1, "nextForm": "Magcargo", "evoTrigger": 8},
  {"id": 219, "name": "Magcargo", "type": "Fogo", "secondType": "Pedra", "BaseTotal": 260, "hp": 60, "atk": 70, "def": 100, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 220, "name": "Swinub", "type": "Gelo", "secondType": "Terra", "BaseTotal": 175, "hp": 50, "atk": 40, "def": 35, "spd": 50, "stage": 1, "nextForm": "Piloswine", "evoTrigger": 5},
  {"id": 221, "name": "Piloswine", "type": "Gelo", "secondType": "Terra", "BaseTotal": 300, "hp": 100, "atk": 80, "def": 70, "spd": 50, "stage": 2, "nextForm": "Mamoswine", "evoTrigger": 10},
  {"id": 222, "name": "Corsola", "type": "Água", "secondType": "Pedra", "BaseTotal": 255, "hp": 65, "atk": 60, "def": 95, "spd": 35, "stage": 1, "nextForm": null},
  {"id": 223, "name": "Remoraid", "type": "Água", "secondType": "", "BaseTotal": 200, "hp": 35, "atk": 65, "def": 35, "spd": 65, "stage": 1, "nextForm": "Octillery", "evoTrigger": 8},
  {"id": 224, "name": "Octillery", "type": "Água", "secondType": "", "BaseTotal": 300, "hp": 75, "atk": 105, "def": 75, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 225, "name": "Delibird", "type": "Gelo", "secondType": "Voador", "BaseTotal": 225, "hp": 45, "atk": 60, "def": 45, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 226, "name": "Mantine", "type": "Água", "secondType": "Voador", "BaseTotal": 300, "hp": 65, "atk": 60, "def": 105, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 227, "name": "Skarmory", "type": "Aço", "secondType": "Voador", "BaseTotal": 300, "hp": 65, "atk": 60, "def": 105, "spd": 70, "stage": 1, "nextForm": null},
  {"id": 228, "name": "Houndour", "type": "Noturno", "secondType": "Fogo", "BaseTotal": 220, "hp": 45, "atk": 70, "def": 40, "spd": 65, "stage": 1, "nextForm": "Houndoom", "evoTrigger": 8},
  {"id": 229, "name": "Houndoom", "type": "Noturno", "secondType": "Fogo", "BaseTotal": 335, "hp": 75, "atk": 100, "def": 65, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 230, "name": "Kingdra", "type": "Água", "secondType": "Dragão", "BaseTotal": 350, "hp": 75, "atk": 95, "def": 95, "spd": 85, "stage": 3, "nextForm": null},
  {"id": 231, "name": "Phanpy", "type": "Terra", "secondType": "", "BaseTotal": 230, "hp": 90, "atk": 50, "def": 50, "spd": 40, "stage": 1, "nextForm": "Donphan", "evoTrigger": 8},
  {"id": 232, "name": "Donphan", "type": "Terra", "secondType": "", "BaseTotal": 320, "hp": 90, "atk": 90, "def": 90, "spd": 50, "stage": 2, "nextForm": null},
  {"id": 233, "name": "Porygon2", "type": "Normal", "secondType": "", "BaseTotal": 329, "hp": 85, "atk": 92, "def": 92, "spd": 60, "stage": 2, "nextForm": "Porygon-Z", "evoTrigger": 10},
  {"id": 234, "name": "Stantler", "type": "Normal", "secondType": "", "BaseTotal": 312, "hp": 73, "atk": 90, "def": 64, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 235, "name": "Smeargle", "type": "Normal", "secondType": "", "BaseTotal": 190, "hp": 55, "atk": 20, "def": 40, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 236, "name": "Tyrogue", "type": "Lutador", "secondType": "", "BaseTotal": 140, "hp": 35, "atk": 35, "def": 35, "spd": 35, "stage": 1, "nextForm": null},
  {"id": 237, "name": "Hitmontop", "type": "Lutador", "secondType": "", "BaseTotal": 287, "hp": 50, "atk": 65, "def": 102, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 238, "name": "Smoochum", "type": "Gelo", "secondType": "Psíquico", "BaseTotal": 208, "hp": 45, "atk": 58, "def": 40, "spd": 65, "stage": 1, "nextForm": "Jynx", "evoTrigger": 8},
  {"id": 239, "name": "Elekid", "type": "Elétrico", "secondType": "", "BaseTotal": 250, "hp": 45, "atk": 64, "def": 46, "spd": 95, "stage": 1, "nextForm": "Electabuzz", "evoTrigger": 5},
  {"id": 240, "name": "Magby", "type": "Fogo", "secondType": "", "BaseTotal": 246, "hp": 45, "atk": 72, "def": 46, "spd": 83, "stage": 1, "nextForm": "Magmar", "evoTrigger": 5},
  {"id": 241, "name": "Miltank", "type": "Normal", "secondType": "", "BaseTotal": 343, "hp": 95, "atk": 60, "def": 88, "spd": 100, "stage": 1, "nextForm": null},
  {"id": 242, "name": "Blissey", "type": "Normal", "secondType": "", "BaseTotal": 424, "hp": 255, "atk": 42, "def": 72, "spd": 55, "stage": 3, "nextForm": null},
  {"id": 243, "name": "Raikou", "type": "Elétrico", "secondType": "", "BaseTotal": 393, "hp": 90, "atk": 100, "def": 88, "spd": 115, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 244, "name": "Entei", "type": "Fogo", "secondType": "", "BaseTotal": 397, "hp": 115, "atk": 102, "def": 80, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 245, "name": "Suicune", "type": "Água", "secondType": "", "BaseTotal": 382, "hp": 100, "atk": 82, "def": 115, "spd": 85, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 246, "name": "Larvitar", "type": "Pedra", "secondType": "Terra", "BaseTotal": 195, "hp": 50, "atk": 54, "def": 50, "spd": 41, "stage": 1, "nextForm": "Pupitar", "evoTrigger": 5},
  {"id": 247, "name": "Pupitar", "type": "Pedra", "secondType": "Terra", "BaseTotal": 265, "hp": 70, "atk": 74, "def": 70, "spd": 51, "stage": 2, "nextForm": "Tyranitar", "evoTrigger": 10},
  {"id": 248, "name": "Tyranitar", "type": "Pedra", "secondType": "Noturno", "BaseTotal": 380, "hp": 100, "atk": 114, "def": 105, "spd": 61, "stage": 3, "nextForm": null},
  {"id": 249, "name": "Lugia", "type": "Psíquico", "secondType": "Voador", "BaseTotal": 448, "hp": 106, "atk": 90, "def": 142, "spd": 110, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 250, "name": "Ho-Oh", "type": "Fogo", "secondType": "Voador", "BaseTotal": 438, "hp": 106, "atk": 120, "def": 122, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 251, "name": "Celebi", "type": "Psíquico", "secondType": "Grama", "BaseTotal": 400, "hp": 100, "atk": 100, "def": 100, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true}
];
