import type { PokemonData } from '../types';

export const GEN4: PokemonData[] = [
  {"id": 387, "name": "Turtwig", "type": "Grama", "secondType": "", "BaseTotal": 202, "hp": 55, "atk": 56, "def": 60, "spd": 31, "stage": 1, "nextForm": "Grotle", "evoTrigger": 5},
  {"id": 388, "name": "Grotle", "type": "Grama", "secondType": "", "BaseTotal": 258, "hp": 75, "atk": 72, "def": 75, "spd": 36, "stage": 2, "nextForm": "Torterra", "evoTrigger": 10},
  {"id": 389, "name": "Torterra", "type": "Grama", "secondType": "Terra", "BaseTotal": 338, "hp": 95, "atk": 92, "def": 95, "spd": 56, "stage": 3, "nextForm": null },
  {"id": 390, "name": "Chimchar", "type": "Fogo", "secondType": "", "BaseTotal": 207, "hp": 44, "atk": 58, "def": 44, "spd": 61, "stage": 1, "nextForm": "Monferno", "evoTrigger": 5},
  {"id": 391, "name": "Monferno", "type": "Fogo", "secondType": "Lutador", "BaseTotal": 275, "hp": 64, "atk": 78, "def": 52, "spd": 81, "stage": 2, "nextForm": "Infernape", "evoTrigger": 10},
  {"id": 392, "name": "Infernape", "type": "Fogo", "secondType": "Lutador", "BaseTotal": 359, "hp": 76, "atk": 104, "def": 71, "spd": 108, "stage": 3, "nextForm": null},
  {"id": 393, "name": "Piplup", "type": "Água", "secondType": "", "BaseTotal": 203, "hp": 53, "atk": 56, "def": 54, "spd": 40, "stage": 1, "nextForm": "Prinplup", "evoTrigger": 5},
  {"id": 394, "name": "Prinplup", "type": "Água", "secondType": "", "BaseTotal": 260, "hp": 64, "atk": 74, "def": 72, "spd": 50, "stage": 2, "nextForm": "Empoleon", "evoTrigger": 10},
  {"id": 395, "name": "Empoleon", "type": "Água", "secondType": "Aço", "BaseTotal": 336, "hp": 84, "atk": 98, "def": 94, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 396, "name": "Starly", "type": "Normal", "secondType": "Voador", "BaseTotal": 172, "hp": 40, "atk": 42, "def": 30, "spd": 60, "stage": 1, "nextForm": "Staravia", "evoTrigger": 5},
  {"id": 397, "name": "Staravia", "type": "Normal", "secondType": "Voador", "BaseTotal": 238, "hp": 55, "atk": 58, "def": 45, "spd": 80, "stage": 2, "nextForm": "Staraptor", "evoTrigger": 10},
  {"id": 398, "name": "Staraptor", "type": "Normal", "secondType": "Voador", "BaseTotal": 335, "hp": 85, "atk": 85, "def": 65, "spd": 100, "stage": 3, "nextForm": null},
  {"id": 399, "name": "Bidoof", "type": "Normal", "secondType": "", "BaseTotal": 170, "hp": 59, "atk": 40, "def": 40, "spd": 31, "stage": 1, "nextForm": "Bibarel", "evoTrigger": 8},
  {"id": 400, "name": "Bibarel", "type": "Normal", "secondType": "Água", "BaseTotal": 280, "hp": 79, "atk": 70, "def": 60, "spd": 71, "stage": 2, "nextForm": null},
  {"id": 401, "name": "Kricketot", "type": "Inseto", "secondType": "", "BaseTotal": 128, "hp": 37, "atk": 25, "def": 41, "spd": 25, "stage": 1, "nextForm": "Kricketune", "evoTrigger": 8},
  {"id": 402, "name": "Kricketune", "type": "Inseto", "secondType": "", "BaseTotal": 263, "hp": 77, "atk": 70, "def": 51, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 403, "name": "Shinx", "type": "Elétrico", "secondType": "", "BaseTotal": 176, "hp": 45, "atk": 52, "def": 34, "spd": 45, "stage": 1, "nextForm": "Luxio", "evoTrigger": 5},
  {"id": 404, "name": "Luxio", "type": "Elétrico", "secondType": "", "BaseTotal": 241, "hp": 60, "atk": 72, "def": 49, "spd": 60, "stage": 2, "nextForm": "Luxray", "evoTrigger": 10},
  {"id": 405, "name": "Luxray", "type": "Elétrico", "secondType": "", "BaseTotal": 337, "hp": 80, "atk": 108, "def": 79, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 406, "name": "Budew", "type": "Grama", "secondType": "Veneno", "BaseTotal": 187, "hp": 40, "atk": 40, "def": 52, "spd": 55, "stage": 1, "nextForm": "Roserade", "evoTrigger": 8},
  {"id": 407, "name": "Roserade", "type": "Grama", "secondType": "Veneno", "BaseTotal": 333, "hp": 60, "atk": 98, "def": 85, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 408, "name": "Cranidos", "type": "Pedra", "secondType": "", "BaseTotal": 238, "hp": 67, "atk": 78, "def": 35, "spd": 58, "stage": 1, "nextForm": "Rampardos", "evoTrigger": 8},
  {"id": 409, "name": "Rampardos", "type": "Pedra", "secondType": "", "BaseTotal": 325, "hp": 97, "atk": 115, "def": 55, "spd": 58, "stage": 2, "nextForm": null},
  {"id": 410, "name": "Shieldon", "type": "Pedra", "secondType": "Aço", "BaseTotal": 205, "hp": 30, "atk": 42, "def": 103, "spd": 30, "stage": 1, "nextForm": "Bastiodon", "evoTrigger": 8},
  {"id": 411, "name": "Bastiodon", "type": "Pedra", "secondType": "Aço", "BaseTotal": 293, "hp": 60, "atk": 50, "def": 153, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 412, "name": "Burmy", "type": "Inseto", "secondType": "", "BaseTotal": 150, "hp": 40, "atk": 29, "def": 45, "spd": 36, "stage": 1, "nextForm": "Wormadam", "evoTrigger": 8},
  {"id": 413, "name": "Wormadam", "type": "Inseto", "secondType": "Grama", "BaseTotal": 260, "hp": 60, "atk": 69, "def": 95, "spd": 36, "stage": 2, "nextForm": null},
  {"id": 414, "name": "Mothim", "type": "Inseto", "secondType": "Voador", "BaseTotal": 280, "hp": 70, "atk": 94, "def": 50, "spd": 66, "stage": 2, "nextForm": null},
  {"id": 415, "name": "Combee", "type": "Inseto", "secondType": "Voador", "BaseTotal": 172, "hp": 30, "atk": 30, "def": 42, "spd": 70, "stage": 1, "nextForm": "Vespiquen", "evoTrigger": 8},
  {"id": 416, "name": "Vespiquen", "type": "Inseto", "secondType": "Voador", "BaseTotal": 292, "hp": 70, "atk": 80, "def": 102, "spd": 40, "stage": 2, "nextForm": null},
  {"id": 417, "name": "Pachirisu", "type": "Elétrico", "secondType": "", "BaseTotal": 280, "hp": 60, "atk": 45, "def": 80, "spd": 95, "stage": 1, "nextForm": null},
  {"id": 418, "name": "Buizel", "type": "Água", "secondType": "", "BaseTotal": 234, "hp": 55, "atk": 62, "def": 32, "spd": 85, "stage": 1, "nextForm": "Floatzel", "evoTrigger": 8},
  {"id": 419, "name": "Floatzel", "type": "Água", "secondType": "", "BaseTotal": 347, "hp": 85, "atk": 95, "def": 52, "spd": 115, "stage": 2, "nextForm": null},
  {"id": 420, "name": "Cherubi", "type": "Grama", "secondType": "", "BaseTotal": 177, "hp": 45, "atk": 48, "def": 49, "spd": 35, "stage": 1, "nextForm": "Cherrim", "evoTrigger": 8},
  {"id": 421, "name": "Cherrim", "type": "Grama", "secondType": "", "BaseTotal": 303, "hp": 70, "atk": 74, "def": 74, "spd": 85, "stage": 2, "nextForm": null},
  {"id": 422, "name": "Shellos", "type": "Água", "secondType": "", "BaseTotal": 217, "hp": 76, "atk": 52, "def": 55, "spd": 34, "stage": 1, "nextForm": "Gastrodon", "evoTrigger": 8},
  {"id": 423, "name": "Gastrodon", "type": "Água", "secondType": "Terra", "BaseTotal": 313, "hp": 111, "atk": 88, "def": 75, "spd": 39, "stage": 2, "nextForm": null},
  {"id": 424, "name": "Ambipom", "type": "Normal", "secondType": "", "BaseTotal": 336, "hp": 75, "atk": 80, "def": 66, "spd": 115, "stage": 2, "nextForm": null},
  {"id": 425, "name": "Drifloon", "type": "Fantasma", "secondType": "Voador", "BaseTotal": 254, "hp": 90, "atk": 55, "def": 39, "spd": 70, "stage": 1, "nextForm": "Drifblim", "evoTrigger": 8},
  {"id": 426, "name": "Drifblim", "type": "Fantasma", "secondType": "Voador", "BaseTotal": 364, "hp": 150, "atk": 85, "def": 49, "spd": 80, "stage": 2, "nextForm": null},
  {"id": 427, "name": "Buneary", "type": "Normal", "secondType": "", "BaseTotal": 245, "hp": 55, "atk": 55, "def": 50, "spd": 85, "stage": 1, "nextForm": "Lopunny", "evoTrigger": 8},
  {"id": 428, "name": "Lopunny", "type": "Normal", "secondType": "", "BaseTotal": 325, "hp": 65, "atk": 65, "def": 90, "spd": 105, "stage": 2, "nextForm": null},
  {"id": 429, "name": "Mismagius", "type": "Fantasma", "secondType": "", "BaseTotal": 329, "hp": 60, "atk": 82, "def": 82, "spd": 105, "stage": 2, "nextForm": null},
  {"id": 430, "name": "Honchkrow", "type": "Noturno", "secondType": "Voador", "BaseTotal": 338, "hp": 100, "atk": 115, "def": 52, "spd": 71, "stage": 2, "nextForm": null},
  {"id": 431, "name": "Glameow", "type": "Normal", "secondType": "", "BaseTotal": 222, "hp": 49, "atk": 48, "def": 40, "spd": 85, "stage": 1, "nextForm": "Purugly", "evoTrigger": 8},
  {"id": 432, "name": "Purugly", "type": "Normal", "secondType": "", "BaseTotal": 318, "hp": 71, "atk": 73, "def": 62, "spd": 112, "stage": 2, "nextForm": null},
  {"id": 433, "name": "Chingling", "type": "Psíquico", "secondType": "", "BaseTotal": 188, "hp": 45, "atk": 48, "def": 50, "spd": 45, "stage": 1, "nextForm": "Chimecho", "evoTrigger": 8},
  {"id": 434, "name": "Stunky", "type": "Veneno", "secondType": "Noturno", "BaseTotal": 233, "hp": 63, "atk": 52, "def": 44, "spd": 74, "stage": 1, "nextForm": "Skuntank", "evoTrigger": 8},
  {"id": 435, "name": "Skuntank", "type": "Veneno", "secondType": "Noturno", "BaseTotal": 333, "hp": 103, "atk": 82, "def": 64, "spd": 84, "stage": 2, "nextForm": null},
  {"id": 436, "name": "Bronzor", "type": "Aço", "secondType": "Psíquico", "BaseTotal": 190, "hp": 57, "atk": 24, "def": 86, "spd": 23, "stage": 1, "nextForm": "Bronzong", "evoTrigger": 8},
  {"id": 437, "name": "Bronzong", "type": "Aço", "secondType": "Psíquico", "BaseTotal": 300, "hp": 67, "atk": 84, "def": 116, "spd": 33, "stage": 2, "nextForm": null},
  {"id": 438, "name": "Bonsly", "type": "Pedra", "secondType": "", "BaseTotal": 175, "hp": 50, "atk": 45, "def": 70, "spd": 10, "stage": 1, "nextForm": "Sudowoodo", "evoTrigger": 8},
  {"id": 439, "name": "Mime Jr.", "type": "Psíquico", "secondType": "Fada", "BaseTotal": 196, "hp": 20, "atk": 48, "def": 68, "spd": 60, "stage": 1, "nextForm": "Mr. Mime", "evoTrigger": 5},
  {"id": 440, "name": "Happiny", "type": "Normal", "secondType": "", "BaseTotal": 175, "hp": 100, "atk": 10, "def": 35, "spd": 30, "stage": 1, "nextForm": "Chansey", "evoTrigger": 5},
  {"id": 441, "name": "Chatot", "type": "Normal", "secondType": "Voador", "BaseTotal": 289, "hp": 76, "atk": 78, "def": 44, "spd": 91, "stage": 1, "nextForm": null},
  {"id": 442, "name": "Spiritomb", "type": "Fantasma", "secondType": "Noturno", "BaseTotal": 285, "hp": 50, "atk": 92, "def": 108, "spd": 35, "stage": 1, "nextForm": null},
  {"id": 443, "name": "Gible", "type": "Dragão", "secondType": "Terra", "BaseTotal": 200, "hp": 58, "atk": 55, "def": 45, "spd": 42, "stage": 1, "nextForm": "Gabite", "evoTrigger": 5},
  {"id": 444, "name": "Gabite", "type": "Dragão", "secondType": "Terra", "BaseTotal": 280, "hp": 68, "atk": 70, "def": 60, "spd": 82, "stage": 2, "nextForm": "Garchomp", "evoTrigger": 10},
  {"id": 445, "name": "Garchomp", "type": "Dragão", "secondType": "Terra", "BaseTotal": 405, "hp": 108, "atk": 105, "def": 90, "spd": 102, "stage": 3, "nextForm": null},
  {"id": 446, "name": "Munchlax", "type": "Normal", "secondType": "", "BaseTotal": 264, "hp": 135, "atk": 62, "def": 62, "spd": 5, "stage": 1, "nextForm": "Snorlax", "evoTrigger": 8},
  {"id": 447, "name": "Riolu", "type": "Lutador", "secondType": "", "BaseTotal": 192, "hp": 40, "atk": 52, "def": 40, "spd": 60, "stage": 1, "nextForm": "Lucario", "evoTrigger": 8},
  {"id": 448, "name": "Lucario", "type": "Lutador", "secondType": "Aço", "BaseTotal": 342, "hp": 70, "atk": 112, "def": 70, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 449, "name": "Hippopotas", "type": "Terra", "secondType": "", "BaseTotal": 215, "hp": 68, "atk": 55, "def": 60, "spd": 32, "stage": 1, "nextForm": "Hippowdon", "evoTrigger": 8},
  {"id": 450, "name": "Hippowdon", "type": "Terra", "secondType": "", "BaseTotal": 340, "hp": 108, "atk": 90, "def": 95, "spd": 47, "stage": 2, "nextForm": null},
  {"id": 451, "name": "Skorupi", "type": "Veneno", "secondType": "Inseto", "BaseTotal": 217, "hp": 40, "atk": 40, "def": 72, "spd": 65, "stage": 1, "nextForm": "Drapion", "evoTrigger": 8},
  {"id": 452, "name": "Drapion", "type": "Veneno", "secondType": "Noturno", "BaseTotal": 332, "hp": 70, "atk": 75, "def": 92, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 453, "name": "Croagunk", "type": "Veneno", "secondType": "Lutador", "BaseTotal": 199, "hp": 48, "atk": 61, "def": 40, "spd": 50, "stage": 1, "nextForm": "Toxicroak", "evoTrigger": 8},
  {"id": 454, "name": "Toxicroak", "type": "Veneno", "secondType": "Lutador", "BaseTotal": 329, "hp": 83, "atk": 96, "def": 65, "spd": 85, "stage": 2, "nextForm": null},
  {"id": 455, "name": "Carnivine", "type": "Grama", "secondType": "", "BaseTotal": 287, "hp": 74, "atk": 95, "def": 72, "spd": 46, "stage": 1, "nextForm": null},
  {"id": 456, "name": "Finneon", "type": "Água", "secondType": "", "BaseTotal": 222, "hp": 49, "atk": 49, "def": 58, "spd": 66, "stage": 1, "nextForm": "Lumineon", "evoTrigger": 8},
  {"id": 457, "name": "Lumineon", "type": "Água", "secondType": "", "BaseTotal": 310, "hp": 69, "atk": 69, "def": 81, "spd": 91, "stage": 2, "nextForm": null},
  {"id": 458, "name": "Mantyke", "type": "Água", "secondType": "Voador", "BaseTotal": 220, "hp": 45, "atk": 40, "def": 85, "spd": 50, "stage": 1, "nextForm": "Mantine", "evoTrigger": 8},
  {"id": 459, "name": "Snover", "type": "Grama", "secondType": "Gelo", "BaseTotal": 217, "hp": 60, "atk": 62, "def": 55, "spd": 40, "stage": 1, "nextForm": "Abomasnow", "evoTrigger": 8},
  {"id": 460, "name": "Abomasnow", "type": "Grama", "secondType": "Gelo", "BaseTotal": 322, "hp": 90, "atk": 92, "def": 80, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 461, "name": "Weavile", "type": "Noturno", "secondType": "Gelo", "BaseTotal": 352, "hp": 70, "atk": 82, "def": 75, "spd": 125, "stage": 2, "nextForm": null},
  {"id": 462, "name": "Magnezone", "type": "Elétrico", "secondType": "Aço", "BaseTotal": 332, "hp": 70, "atk": 100, "def": 102, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 463, "name": "Lickilicky", "type": "Normal", "secondType": "", "BaseTotal": 337, "hp": 110, "atk": 82, "def": 95, "spd": 50, "stage": 2, "nextForm": null},
  {"id": 464, "name": "Rhyperior", "type": "Terra", "secondType": "Pedra", "BaseTotal": 345, "hp": 115, "atk": 98, "def": 92, "spd": 40, "stage": 3, "nextForm": null},
  {"id": 465, "name": "Tangrowth", "type": "Grama", "secondType": "", "BaseTotal": 343, "hp": 100, "atk": 105, "def": 88, "spd": 50, "stage": 2, "nextForm": null},
  {"id": 466, "name": "Electivire", "type": "Elétrico", "secondType": "", "BaseTotal": 355, "hp": 75, "atk": 109, "def": 76, "spd": 95, "stage": 3, "nextForm": null},
  {"id": 467, "name": "Magmortar", "type": "Fogo", "secondType": "", "BaseTotal": 349, "hp": 75, "atk": 110, "def": 81, "spd": 83, "stage": 3, "nextForm": null},
  {"id": 468, "name": "Togekiss", "type": "Fada", "secondType": "Voador", "BaseTotal": 355, "hp": 85, "atk": 85, "def": 105, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 469, "name": "Yanmega", "type": "Inseto", "secondType": "Voador", "BaseTotal": 348, "hp": 86, "atk": 96, "def": 71, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 470, "name": "Leafeon", "type": "Grama", "secondType": "", "BaseTotal": 343, "hp": 65, "atk": 85, "def": 98, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 471, "name": "Glaceon", "type": "Gelo", "secondType": "", "BaseTotal": 327, "hp": 65, "atk": 95, "def": 102, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 472, "name": "Gliscor", "type": "Terra", "secondType": "Voador", "BaseTotal": 340, "hp": 75, "atk": 70, "def": 100, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 473, "name": "Mamoswine", "type": "Gelo", "secondType": "Terra", "BaseTotal": 360, "hp": 110, "atk": 100, "def": 70, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 474, "name": "Porygon-Z", "type": "Normal", "secondType": "", "BaseTotal": 355, "hp": 85, "atk": 108, "def": 72, "spd": 90, "stage": 3, "nextForm": null},
  {"id": 475, "name": "Gallade", "type": "Psíquico", "secondType": "Lutador", "BaseTotal": 333, "hp": 68, "atk": 95, "def": 90, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 476, "name": "Probopass", "type": "Pedra", "secondType": "Aço", "BaseTotal": 313, "hp": 60, "atk": 65, "def": 148, "spd": 40, "stage": 2, "nextForm": null},
  {"id": 477, "name": "Dusknoir", "type": "Fantasma", "secondType": "", "BaseTotal": 307, "hp": 45, "atk": 82, "def": 135, "spd": 45, "stage": 3, "nextForm": null},
  {"id": 478, "name": "Froslass", "type": "Gelo", "secondType": "Fantasma", "BaseTotal": 330, "hp": 70, "atk": 80, "def": 70, "spd": 110, "stage": 2, "nextForm": null},
  {"id": 479, "name": "Rotom", "type": "Elétrico", "secondType": "Fantasma", "BaseTotal": 290, "hp": 50, "atk": 72, "def": 77, "spd": 91, "stage": 1, "nextForm": null},
  {"id": 480, "name": "Uxie", "type": "Psíquico", "secondType": "", "BaseTotal": 375, "hp": 75, "atk": 75, "def": 130, "spd": 95, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 481, "name": "Mesprit", "type": "Psíquico", "secondType": "", "BaseTotal": 370, "hp": 80, "atk": 105, "def": 105, "spd": 80, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 482, "name": "Azelf", "type": "Psíquico", "secondType": "", "BaseTotal": 385, "hp": 75, "atk": 125, "def": 70, "spd": 115, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 483, "name": "Dialga", "type": "Aço", "secondType": "Dragão", "BaseTotal": 435, "hp": 100, "atk": 135, "def": 110, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 484, "name": "Palkia", "type": "Água", "secondType": "Dragão", "BaseTotal": 435, "hp": 90, "atk": 135, "def": 110, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 485, "name": "Heatran", "type": "Fogo", "secondType": "Aço", "BaseTotal": 384, "hp": 91, "atk": 110, "def": 106, "spd": 77, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 486, "name": "Regigigas", "type": "Normal", "secondType": "", "BaseTotal": 440, "hp": 110, "atk": 120, "def": 110, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 487, "name": "Giratina", "type": "Fantasma", "secondType": "Dragão", "BaseTotal": 460, "hp": 150, "atk": 100, "def": 120, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 488, "name": "Cresselia", "type": "Psíquico", "secondType": "", "BaseTotal": 402, "hp": 120, "atk": 72, "def": 125, "spd": 85, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 489, "name": "Phione", "type": "Água", "secondType": "", "BaseTotal": 320, "hp": 80, "atk": 80, "def": 80, "spd": 80, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 490, "name": "Manaphy", "type": "Água", "secondType": "", "BaseTotal": 400, "hp": 100, "atk": 100, "def": 100, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 491, "name": "Darkrai", "type": "Noturno", "secondType": "", "BaseTotal": 397, "hp": 70, "atk": 112, "def": 90, "spd": 125, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 492, "name": "Shaymin", "type": "Grama", "secondType": "", "BaseTotal": 400, "hp": 100, "atk": 100, "def": 100, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 493, "name": "Arceus", "type": "Normal", "secondType": "", "BaseTotal": 480, "hp": 120, "atk": 120, "def": 120, "spd": 120, "stage": 1, "nextForm": null, "isLegendary": true}
];
