import type { PokemonData } from '../types';

export const GEN5: PokemonData[] = [
  {"id": 494, "name": "Victini", "type": "Psíquico", "secondType": "Fogo", "BaseTotal": 400, "hp": 100, "atk": 100, "def": 100, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 495, "name": "Snivy", "type": "Grama", "secondType": "", "BaseTotal": 208, "hp": 45, "atk": 45, "def": 55, "spd": 63, "stage": 1, "nextForm": "Servine", "evoTrigger": 5},
  {"id": 496, "name": "Servine", "type": "Grama", "secondType": "", "BaseTotal": 278, "hp": 60, "atk": 60, "def": 75, "spd": 83, "stage": 2, "nextForm": "Serperior", "evoTrigger": 10},
  {"id": 497, "name": "Serperior", "type": "Grama", "secondType": "", "BaseTotal": 358, "hp": 75, "atk": 75, "def": 95, "spd": 113, "stage": 3, "nextForm": null},
  {"id": 498, "name": "Tepig", "type": "Fogo", "secondType": "", "BaseTotal": 209, "hp": 65, "atk": 54, "def": 45, "spd": 45, "stage": 1, "nextForm": "Pignite", "evoTrigger": 5},
  {"id": 499, "name": "Pignite", "type": "Fogo", "secondType": "Lutador", "BaseTotal": 282, "hp": 90, "atk": 82, "def": 55, "spd": 55, "stage": 2, "nextForm": "Emboar", "evoTrigger": 10},
  {"id": 500, "name": "Emboar", "type": "Fogo", "secondType": "Lutador", "BaseTotal": 352, "hp": 110, "atk": 112, "def": 65, "spd": 65, "stage": 3, "nextForm": null},
  {"id": 501, "name": "Oshawott", "type": "Água", "secondType": "", "BaseTotal": 204, "hp": 55, "atk": 59, "def": 45, "spd": 45, "stage": 1, "nextForm": "Dewott", "evoTrigger": 5},
  {"id": 502, "name": "Dewott", "type": "Água", "secondType": "", "BaseTotal": 274, "hp": 75, "atk": 79, "def": 60, "spd": 60, "stage": 2, "nextForm": "Samurott", "evoTrigger": 10},
  {"id": 503, "name": "Samurott", "type": "Água", "secondType": "", "BaseTotal": 347, "hp": 95, "atk": 104, "def": 78, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 504, "name": "Patrat", "type": "Normal", "secondType": "", "BaseTotal": 171, "hp": 45, "atk": 45, "def": 39, "spd": 42, "stage": 1, "nextForm": "Watchog", "evoTrigger": 8},
  {"id": 505, "name": "Watchog", "type": "Normal", "secondType": "", "BaseTotal": 278, "hp": 60, "atk": 72, "def": 69, "spd": 77, "stage": 2, "nextForm": null},
  {"id": 506, "name": "Lillipup", "type": "Normal", "secondType": "", "BaseTotal": 187, "hp": 45, "atk": 42, "def": 45, "spd": 55, "stage": 1, "nextForm": "Herdier", "evoTrigger": 5},
  {"id": 507, "name": "Herdier", "type": "Normal", "secondType": "", "BaseTotal": 248, "hp": 65, "atk": 58, "def": 65, "spd": 60, "stage": 2, "nextForm": "Stoutland", "evoTrigger": 10},
  {"id": 508, "name": "Stoutland", "type": "Normal", "secondType": "", "BaseTotal": 333, "hp": 85, "atk": 78, "def": 90, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 509, "name": "Purrloin", "type": "Noturno", "secondType": "", "BaseTotal": 194, "hp": 41, "atk": 50, "def": 37, "spd": 66, "stage": 1, "nextForm": "Liepard", "evoTrigger": 8},
  {"id": 510, "name": "Liepard", "type": "Noturno", "secondType": "", "BaseTotal": 308, "hp": 64, "atk": 88, "def": 50, "spd": 106, "stage": 2, "nextForm": null},
  {"id": 511, "name": "Pansage", "type": "Grama", "secondType": "", "BaseTotal": 215, "hp": 50, "atk": 53, "def": 48, "spd": 64, "stage": 1, "nextForm": "Simisage", "evoTrigger": 8},
  {"id": 512, "name": "Simisage", "type": "Grama", "secondType": "", "BaseTotal": 337, "hp": 75, "atk": 98, "def": 63, "spd": 101, "stage": 2, "nextForm": null},
  {"id": 513, "name": "Pansear", "type": "Fogo", "secondType": "", "BaseTotal": 215, "hp": 50, "atk": 53, "def": 48, "spd": 64, "stage": 1, "nextForm": "Simisear", "evoTrigger": 8},
  {"id": 514, "name": "Simisear", "type": "Fogo", "secondType": "", "BaseTotal": 337, "hp": 75, "atk": 98, "def": 63, "spd": 101, "stage": 2, "nextForm": null},
  {"id": 515, "name": "Panpour", "type": "Água", "secondType": "", "BaseTotal": 215, "hp": 50, "atk": 53, "def": 48, "spd": 64, "stage": 1, "nextForm": "Simipour", "evoTrigger": 8},
  {"id": 516, "name": "Simipour", "type": "Água", "secondType": "", "BaseTotal": 337, "hp": 75, "atk": 98, "def": 63, "spd": 101, "stage": 2, "nextForm": null},
  {"id": 517, "name": "Munna", "type": "Psíquico", "secondType": "", "BaseTotal": 196, "hp": 76, "atk": 46, "def": 50, "spd": 24, "stage": 1, "nextForm": "Musharna", "evoTrigger": 8},
  {"id": 518, "name": "Musharna", "type": "Psíquico", "secondType": "", "BaseTotal": 316, "hp": 116, "atk": 81, "def": 90, "spd": 29, "stage": 2, "nextForm": null},
  {"id": 519, "name": "Pidove", "type": "Normal", "secondType": "Voador", "BaseTotal": 179, "hp": 50, "atk": 46, "def": 40, "spd": 43, "stage": 1, "nextForm": "Tranquill", "evoTrigger": 5},
  {"id": 520, "name": "Tranquill", "type": "Normal", "secondType": "Voador", "BaseTotal": 243, "hp": 62, "atk": 64, "def": 52, "spd": 65, "stage": 2, "nextForm": "Unfezant", "evoTrigger": 10},
  {"id": 521, "name": "Unfezant", "type": "Normal", "secondType": "Voador", "BaseTotal": 331, "hp": 80, "atk": 90, "def": 68, "spd": 93, "stage": 3, "nextForm": null},
  {"id": 522, "name": "Blitzle", "type": "Elétrico", "secondType": "", "BaseTotal": 208, "hp": 45, "atk": 55, "def": 32, "spd": 76, "stage": 1, "nextForm": "Zebstrika", "evoTrigger": 8},
  {"id": 523, "name": "Zebstrika", "type": "Elétrico", "secondType": "", "BaseTotal": 344, "hp": 75, "atk": 90, "def": 63, "spd": 116, "stage": 2, "nextForm": null},
  {"id": 524, "name": "Roggenrola", "type": "Pedra", "secondType": "", "BaseTotal": 175, "hp": 55, "atk": 50, "def": 55, "spd": 15, "stage": 1, "nextForm": "Boldore", "evoTrigger": 5},
  {"id": 525, "name": "Boldore", "type": "Pedra", "secondType": "", "BaseTotal": 240, "hp": 70, "atk": 78, "def": 72, "spd": 20, "stage": 2, "nextForm": "Gigalith", "evoTrigger": 10},
  {"id": 526, "name": "Gigalith", "type": "Pedra", "secondType": "", "BaseTotal": 313, "hp": 85, "atk": 98, "def": 105, "spd": 25, "stage": 3, "nextForm": null},
  {"id": 527, "name": "Woobat", "type": "Psíquico", "secondType": "Voador", "BaseTotal": 220, "hp": 55, "atk": 50, "def": 43, "spd": 72, "stage": 1, "nextForm": "Swoobat", "evoTrigger": 8},
  {"id": 528, "name": "Swoobat", "type": "Psíquico", "secondType": "Voador", "BaseTotal": 303, "hp": 67, "atk": 67, "def": 55, "spd": 114, "stage": 2, "nextForm": null},
  {"id": 529, "name": "Drilbur", "type": "Terra", "secondType": "", "BaseTotal": 228, "hp": 60, "atk": 58, "def": 42, "spd": 68, "stage": 1, "nextForm": "Excadrill", "evoTrigger": 8},
  {"id": 530, "name": "Excadrill", "type": "Terra", "secondType": "Aço", "BaseTotal": 352, "hp": 110, "atk": 92, "def": 62, "spd": 88, "stage": 2, "nextForm": null},
  {"id": 531, "name": "Audino", "type": "Normal", "secondType": "", "BaseTotal": 299, "hp": 103, "atk": 60, "def": 86, "spd": 50, "stage": 1, "nextForm": null},
  {"id": 532, "name": "Timburr", "type": "Lutador", "secondType": "", "BaseTotal": 207, "hp": 75, "atk": 52, "def": 45, "spd": 35, "stage": 1, "nextForm": "Gurdurr", "evoTrigger": 5},
  {"id": 533, "name": "Gurdurr", "type": "Lutador", "secondType": "", "BaseTotal": 265, "hp": 85, "atk": 72, "def": 68, "spd": 40, "stage": 2, "nextForm": "Conkeldurr", "evoTrigger": 10},
  {"id": 534, "name": "Conkeldurr", "type": "Lutador", "secondType": "", "BaseTotal": 328, "hp": 105, "atk": 98, "def": 80, "spd": 45, "stage": 3, "nextForm": null},
  {"id": 535, "name": "Tympole", "type": "Água", "secondType": "", "BaseTotal": 204, "hp": 50, "atk": 50, "def": 40, "spd": 64, "stage": 1, "nextForm": "Palpitoad", "evoTrigger": 5},
  {"id": 536, "name": "Palpitoad", "type": "Água", "secondType": "Terra", "BaseTotal": 264, "hp": 75, "atk": 65, "def": 55, "spd": 69, "stage": 2, "nextForm": "Seismitoad", "evoTrigger": 10},
  {"id": 537, "name": "Seismitoad", "type": "Água", "secondType": "Terra", "BaseTotal": 344, "hp": 105, "atk": 90, "def": 75, "spd": 74, "stage": 3, "nextForm": null},
  {"id": 538, "name": "Throh", "type": "Lutador", "secondType": "", "BaseTotal": 315, "hp": 120, "atk": 65, "def": 85, "spd": 45, "stage": 1, "nextForm": null},
  {"id": 539, "name": "Sawk", "type": "Lutador", "secondType": "", "BaseTotal": 313, "hp": 75, "atk": 78, "def": 75, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 540, "name": "Sewaddle", "type": "Inseto", "secondType": "Grama", "BaseTotal": 198, "hp": 45, "atk": 46, "def": 65, "spd": 42, "stage": 1, "nextForm": "Swadloon", "evoTrigger": 5},
  {"id": 541, "name": "Swadloon", "type": "Inseto", "secondType": "Grama", "BaseTotal": 238, "hp": 55, "atk": 56, "def": 85, "spd": 42, "stage": 2, "nextForm": "Leavanny", "evoTrigger": 10},
  {"id": 542, "name": "Leavanny", "type": "Inseto", "secondType": "Grama", "BaseTotal": 333, "hp": 75, "atk": 86, "def": 80, "spd": 92, "stage": 3, "nextForm": null},
  {"id": 543, "name": "Venipede", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 174, "hp": 30, "atk": 38, "def": 49, "spd": 57, "stage": 1, "nextForm": "Whirlipede", "evoTrigger": 5},
  {"id": 544, "name": "Whirlipede", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 224, "hp": 40, "atk": 48, "def": 89, "spd": 47, "stage": 2, "nextForm": "Scolipede", "evoTrigger": 10},
  {"id": 545, "name": "Scolipede", "type": "Inseto", "secondType": "Veneno", "BaseTotal": 329, "hp": 60, "atk": 78, "def": 79, "spd": 112, "stage": 3, "nextForm": null},
  {"id": 546, "name": "Cottonee", "type": "Grama", "secondType": "Fada", "BaseTotal": 193, "hp": 40, "atk": 32, "def": 55, "spd": 66, "stage": 1, "nextForm": "Whimsicott", "evoTrigger": 8},
  {"id": 547, "name": "Whimsicott", "type": "Grama", "secondType": "Fada", "BaseTotal": 328, "hp": 60, "atk": 72, "def": 80, "spd": 116, "stage": 2, "nextForm": null},
  {"id": 548, "name": "Petilil", "type": "Grama", "secondType": "", "BaseTotal": 177, "hp": 45, "atk": 52, "def": 50, "spd": 30, "stage": 1, "nextForm": "Lilligant", "evoTrigger": 8},
  {"id": 549, "name": "Lilligant", "type": "Grama", "secondType": "", "BaseTotal": 320, "hp": 70, "atk": 85, "def": 75, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 550, "name": "Basculin", "type": "Água", "secondType": "", "BaseTotal": 314, "hp": 70, "atk": 86, "def": 60, "spd": 98, "stage": 1, "nextForm": null},
  {"id": 551, "name": "Sandile", "type": "Terra", "secondType": "Noturno", "BaseTotal": 204, "hp": 50, "atk": 54, "def": 35, "spd": 65, "stage": 1, "nextForm": "Krokorok", "evoTrigger": 5},
  {"id": 552, "name": "Krokorok", "type": "Terra", "secondType": "Noturno", "BaseTotal": 243, "hp": 60, "atk": 64, "def": 45, "spd": 74, "stage": 2, "nextForm": "Krookodile", "evoTrigger": 10},
  {"id": 553, "name": "Krookodile", "type": "Terra", "secondType": "Noturno", "BaseTotal": 353, "hp": 95, "atk": 91, "def": 75, "spd": 92, "stage": 3, "nextForm": null},
  {"id": 554, "name": "Darumaka", "type": "Fogo", "secondType": "", "BaseTotal": 217, "hp": 70, "atk": 52, "def": 45, "spd": 50, "stage": 1, "nextForm": "Darmanitan", "evoTrigger": 8},
  {"id": 555, "name": "Darmanitan", "type": "Fogo", "secondType": "", "BaseTotal": 340, "hp": 105, "atk": 85, "def": 55, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 556, "name": "Maractus", "type": "Grama", "secondType": "", "BaseTotal": 298, "hp": 75, "atk": 96, "def": 67, "spd": 60, "stage": 1, "nextForm": null},
  {"id": 557, "name": "Dwebble", "type": "Inseto", "secondType": "Pedra", "BaseTotal": 215, "hp": 50, "atk": 50, "def": 60, "spd": 55, "stage": 1, "nextForm": "Crustle", "evoTrigger": 8},
  {"id": 558, "name": "Crustle", "type": "Inseto", "secondType": "Pedra", "BaseTotal": 300, "hp": 70, "atk": 85, "def": 100, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 559, "name": "Scraggy", "type": "Noturno", "secondType": "Lutador", "BaseTotal": 223, "hp": 50, "atk": 55, "def": 70, "spd": 48, "stage": 1, "nextForm": "Scrafty", "evoTrigger": 8},
  {"id": 560, "name": "Scrafty", "type": "Noturno", "secondType": "Lutador", "BaseTotal": 306, "hp": 65, "atk": 68, "def": 115, "spd": 58, "stage": 2, "nextForm": null},
  {"id": 561, "name": "Sigilyph", "type": "Psíquico", "secondType": "Voador", "BaseTotal": 329, "hp": 72, "atk": 80, "def": 80, "spd": 97, "stage": 1, "nextForm": null},
  {"id": 562, "name": "Yamask", "type": "Fantasma", "secondType": "", "BaseTotal": 185, "hp": 38, "atk": 42, "def": 75, "spd": 30, "stage": 1, "nextForm": "Cofagrigus", "evoTrigger": 8},
  {"id": 563, "name": "Cofagrigus", "type": "Fantasma", "secondType": "", "BaseTotal": 285, "hp": 58, "atk": 72, "def": 125, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 564, "name": "Tirtouga", "type": "Água", "secondType": "Pedra", "BaseTotal": 216, "hp": 54, "atk": 66, "def": 74, "spd": 22, "stage": 1, "nextForm": "Carracosta", "evoTrigger": 8},
  {"id": 565, "name": "Carracosta", "type": "Água", "secondType": "Pedra", "BaseTotal": 301, "hp": 74, "atk": 96, "def": 99, "spd": 32, "stage": 2, "nextForm": null},
  {"id": 566, "name": "Archen", "type": "Pedra", "secondType": "Voador", "BaseTotal": 263, "hp": 55, "atk": 93, "def": 45, "spd": 70, "stage": 1, "nextForm": "Archeops", "evoTrigger": 8},
  {"id": 567, "name": "Archeops", "type": "Pedra", "secondType": "Voador", "BaseTotal": 376, "hp": 75, "atk": 126, "def": 65, "spd": 110, "stage": 2, "nextForm": null},
  {"id": 568, "name": "Trubbish", "type": "Veneno", "secondType": "", "BaseTotal": 222, "hp": 50, "atk": 45, "def": 62, "spd": 65, "stage": 1, "nextForm": "Garbodor", "evoTrigger": 8},
  {"id": 569, "name": "Garbodor", "type": "Veneno", "secondType": "", "BaseTotal": 315, "hp": 80, "atk": 78, "def": 82, "spd": 75, "stage": 2, "nextForm": null},
  {"id": 570, "name": "Zorua", "type": "Noturno", "secondType": "", "BaseTotal": 217, "hp": 40, "atk": 72, "def": 40, "spd": 65, "stage": 1, "nextForm": "Zoroark", "evoTrigger": 8},
  {"id": 571, "name": "Zoroark", "type": "Noturno", "secondType": "", "BaseTotal": 337, "hp": 60, "atk": 112, "def": 60, "spd": 105, "stage": 2, "nextForm": null},
  {"id": 572, "name": "Minccino", "type": "Normal", "secondType": "", "BaseTotal": 215, "hp": 55, "atk": 45, "def": 40, "spd": 75, "stage": 1, "nextForm": "Cinccino", "evoTrigger": 8},
  {"id": 573, "name": "Cinccino", "type": "Normal", "secondType": "", "BaseTotal": 330, "hp": 75, "atk": 80, "def": 60, "spd": 115, "stage": 2, "nextForm": null},
  {"id": 574, "name": "Gothita", "type": "Psíquico", "secondType": "", "BaseTotal": 190, "hp": 45, "atk": 42, "def": 58, "spd": 45, "stage": 1, "nextForm": "Gothorita", "evoTrigger": 5},
  {"id": 575, "name": "Gothorita", "type": "Psíquico", "secondType": "", "BaseTotal": 253, "hp": 60, "atk": 60, "def": 78, "spd": 55, "stage": 2, "nextForm": "Gothitelle", "evoTrigger": 10},
  {"id": 576, "name": "Gothitelle", "type": "Psíquico", "secondType": "", "BaseTotal": 312, "hp": 70, "atk": 75, "def": 102, "spd": 65, "stage": 3, "nextForm": null},
  {"id": 577, "name": "Solosis", "type": "Psíquico", "secondType": "", "BaseTotal": 178, "hp": 45, "atk": 68, "def": 45, "spd": 20, "stage": 1, "nextForm": "Duosion", "evoTrigger": 5},
  {"id": 578, "name": "Duosion", "type": "Psíquico", "secondType": "", "BaseTotal": 232, "hp": 65, "atk": 82, "def": 55, "spd": 30, "stage": 2, "nextForm": "Reuniclus", "evoTrigger": 10},
  {"id": 579, "name": "Reuniclus", "type": "Psíquico", "secondType": "", "BaseTotal": 315, "hp": 110, "atk": 95, "def": 80, "spd": 30, "stage": 3, "nextForm": null},
  {"id": 580, "name": "Ducklett", "type": "Água", "secondType": "Voador", "BaseTotal": 211, "hp": 62, "atk": 44, "def": 50, "spd": 55, "stage": 1, "nextForm": "Swanna", "evoTrigger": 8},
  {"id": 581, "name": "Swanna", "type": "Água", "secondType": "Voador", "BaseTotal": 323, "hp": 75, "atk": 87, "def": 63, "spd": 98, "stage": 2, "nextForm": null},
  {"id": 582, "name": "Vanillite", "type": "Gelo", "secondType": "", "BaseTotal": 193, "hp": 36, "atk": 58, "def": 55, "spd": 44, "stage": 1, "nextForm": "Vanillish", "evoTrigger": 5},
  {"id": 583, "name": "Vanillish", "type": "Gelo", "secondType": "", "BaseTotal": 252, "hp": 51, "atk": 72, "def": 70, "spd": 59, "stage": 2, "nextForm": "Vanilluxe", "evoTrigger": 10},
  {"id": 584, "name": "Vanilluxe", "type": "Gelo", "secondType": "", "BaseTotal": 342, "hp": 71, "atk": 102, "def": 90, "spd": 79, "stage": 3, "nextForm": null},
  {"id": 585, "name": "Deerling", "type": "Normal", "secondType": "Grama", "BaseTotal": 235, "hp": 60, "atk": 50, "def": 50, "spd": 75, "stage": 1, "nextForm": "Sawsbuck", "evoTrigger": 8},
  {"id": 586, "name": "Sawsbuck", "type": "Normal", "secondType": "Grama", "BaseTotal": 325, "hp": 80, "atk": 80, "def": 70, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 587, "name": "Emolga", "type": "Elétrico", "secondType": "Voador", "BaseTotal": 293, "hp": 55, "atk": 75, "def": 60, "spd": 103, "stage": 1, "nextForm": null},
  {"id": 588, "name": "Karrablast", "type": "Inseto", "secondType": "", "BaseTotal": 213, "hp": 50, "atk": 58, "def": 45, "spd": 60, "stage": 1, "nextForm": "Escavalier", "evoTrigger": 8},
  {"id": 589, "name": "Escavalier", "type": "Inseto", "secondType": "Aço", "BaseTotal": 293, "hp": 70, "atk": 98, "def": 105, "spd": 20, "stage": 2, "nextForm": null},
  {"id": 590, "name": "Foongus", "type": "Grama", "secondType": "Veneno", "BaseTotal": 189, "hp": 69, "atk": 55, "def": 50, "spd": 15, "stage": 1, "nextForm": "Amoonguss", "evoTrigger": 8},
  {"id": 591, "name": "Amoonguss", "type": "Grama", "secondType": "Veneno", "BaseTotal": 304, "hp": 114, "atk": 85, "def": 75, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 592, "name": "Frillish", "type": "Água", "secondType": "Fantasma", "BaseTotal": 215, "hp": 55, "atk": 52, "def": 68, "spd": 40, "stage": 1, "nextForm": "Jellicent", "evoTrigger": 8},
  {"id": 593, "name": "Jellicent", "type": "Água", "secondType": "Fantasma", "BaseTotal": 320, "hp": 100, "atk": 72, "def": 88, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 594, "name": "Alomomola", "type": "Água", "secondType": "", "BaseTotal": 350, "hp": 165, "atk": 58, "def": 62, "spd": 65, "stage": 1, "nextForm": null},
  {"id": 595, "name": "Joltik", "type": "Inseto", "secondType": "Elétrico", "BaseTotal": 217, "hp": 50, "atk": 52, "def": 50, "spd": 65, "stage": 1, "nextForm": "Galvantula", "evoTrigger": 8},
  {"id": 596, "name": "Galvantula", "type": "Inseto", "secondType": "Elétrico", "BaseTotal": 325, "hp": 70, "atk": 87, "def": 60, "spd": 108, "stage": 2, "nextForm": null},
  {"id": 597, "name": "Ferroseed", "type": "Grama", "secondType": "Aço", "BaseTotal": 179, "hp": 44, "atk": 37, "def": 88, "spd": 10, "stage": 1, "nextForm": "Ferrothorn", "evoTrigger": 8},
  {"id": 598, "name": "Ferrothorn", "type": "Grama", "secondType": "Aço", "BaseTotal": 292, "hp": 74, "atk": 74, "def": 124, "spd": 20, "stage": 2, "nextForm": null},
  {"id": 599, "name": "Klink", "type": "Aço", "secondType": "", "BaseTotal": 185, "hp": 40, "atk": 50, "def": 65, "spd": 30, "stage": 1, "nextForm": "Klang", "evoTrigger": 5},
  {"id": 600, "name": "Klang", "type": "Aço", "secondType": "", "BaseTotal": 275, "hp": 60, "atk": 75, "def": 90, "spd": 50, "stage": 2, "nextForm": "Klinklang", "evoTrigger": 10},
  {"id": 601, "name": "Klinklang", "type": "Aço", "secondType": "", "BaseTotal": 335, "hp": 60, "atk": 85, "def": 100, "spd": 90, "stage": 3, "nextForm": null},
  {"id": 602, "name": "Tynamo", "type": "Elétrico", "secondType": "", "BaseTotal": 185, "hp": 35, "atk": 50, "def": 40, "spd": 60, "stage": 1, "nextForm": "Eelektrik", "evoTrigger": 5},
  {"id": 603, "name": "Eelektrik", "type": "Elétrico", "secondType": "", "BaseTotal": 255, "hp": 65, "atk": 80, "def": 70, "spd": 40, "stage": 2, "nextForm": "Eelektross", "evoTrigger": 10},
  {"id": 604, "name": "Eelektross", "type": "Elétrico", "secondType": "", "BaseTotal": 325, "hp": 85, "atk": 110, "def": 80, "spd": 50, "stage": 3, "nextForm": null},
  {"id": 605, "name": "Elgyem", "type": "Psíquico", "secondType": "", "BaseTotal": 210, "hp": 55, "atk": 70, "def": 55, "spd": 30, "stage": 1, "nextForm": "Beheeyem", "evoTrigger": 8},
  {"id": 606, "name": "Beheeyem", "type": "Psíquico", "secondType": "", "BaseTotal": 300, "hp": 75, "atk": 100, "def": 85, "spd": 40, "stage": 2, "nextForm": null},
  {"id": 607, "name": "Litwick", "type": "Fantasma", "secondType": "Fogo", "BaseTotal": 173, "hp": 50, "atk": 48, "def": 55, "spd": 20, "stage": 1, "nextForm": "Lampent", "evoTrigger": 5},
  {"id": 608, "name": "Lampent", "type": "Fantasma", "secondType": "Fogo", "BaseTotal": 243, "hp": 60, "atk": 68, "def": 60, "spd": 55, "stage": 2, "nextForm": "Chandelure", "evoTrigger": 10},
  {"id": 609, "name": "Chandelure", "type": "Fantasma", "secondType": "Fogo", "BaseTotal": 330, "hp": 60, "atk": 100, "def": 90, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 610, "name": "Axew", "type": "Dragão", "secondType": "", "BaseTotal": 211, "hp": 46, "atk": 58, "def": 50, "spd": 57, "stage": 1, "nextForm": "Fraxure", "evoTrigger": 5},
  {"id": 611, "name": "Fraxure", "type": "Dragão", "secondType": "", "BaseTotal": 271, "hp": 66, "atk": 78, "def": 60, "spd": 67, "stage": 2, "nextForm": "Haxorus", "evoTrigger": 10},
  {"id": 612, "name": "Haxorus", "type": "Dragão", "secondType": "", "BaseTotal": 357, "hp": 76, "atk": 104, "def": 80, "spd": 97, "stage": 3, "nextForm": null},
  {"id": 613, "name": "Cubchoo", "type": "Gelo", "secondType": "", "BaseTotal": 200, "hp": 55, "atk": 65, "def": 40, "spd": 40, "stage": 1, "nextForm": "Beartic", "evoTrigger": 8},
  {"id": 614, "name": "Beartic", "type": "Gelo", "secondType": "", "BaseTotal": 325, "hp": 95, "atk": 100, "def": 80, "spd": 50, "stage": 2, "nextForm": null},
  {"id": 615, "name": "Cryogonal", "type": "Gelo", "secondType": "", "BaseTotal": 349, "hp": 80, "atk": 72, "def": 92, "spd": 105, "stage": 1, "nextForm": null},
  {"id": 616, "name": "Shelmet", "type": "Inseto", "secondType": "", "BaseTotal": 190, "hp": 50, "atk": 40, "def": 75, "spd": 25, "stage": 1, "nextForm": "Accelgor", "evoTrigger": 8},
  {"id": 617, "name": "Accelgor", "type": "Inseto", "secondType": "", "BaseTotal": 360, "hp": 80, "atk": 85, "def": 50, "spd": 145, "stage": 2, "nextForm": null},
  {"id": 618, "name": "Stunfisk", "type": "Terra", "secondType": "Elétrico", "BaseTotal": 307, "hp": 109, "atk": 74, "def": 92, "spd": 32, "stage": 1, "nextForm": null},
  {"id": 619, "name": "Mienfoo", "type": "Lutador", "secondType": "", "BaseTotal": 230, "hp": 45, "atk": 70, "def": 50, "spd": 65, "stage": 1, "nextForm": "Mienshao", "evoTrigger": 8},
  {"id": 620, "name": "Mienshao", "type": "Lutador", "secondType": "", "BaseTotal": 340, "hp": 65, "atk": 110, "def": 60, "spd": 105, "stage": 2, "nextForm": null},
  {"id": 621, "name": "Druddigon", "type": "Dragão", "secondType": "", "BaseTotal": 305, "hp": 77, "atk": 90, "def": 90, "spd": 48, "stage": 1, "nextForm": null},
  {"id": 622, "name": "Golett", "type": "Terra", "secondType": "Fantasma", "BaseTotal": 198, "hp": 59, "atk": 54, "def": 50, "spd": 35, "stage": 1, "nextForm": "Golurk", "evoTrigger": 8},
  {"id": 623, "name": "Golurk", "type": "Terra", "secondType": "Fantasma", "BaseTotal": 314, "hp": 89, "atk": 90, "def": 80, "spd": 55, "stage": 2, "nextForm": null},
  {"id": 624, "name": "Pawniard", "type": "Noturno", "secondType": "Aço", "BaseTotal": 222, "hp": 45, "atk": 62, "def": 55, "spd": 60, "stage": 1, "nextForm": "Bisharp", "evoTrigger": 5},
  {"id": 625, "name": "Bisharp", "type": "Noturno", "secondType": "Aço", "BaseTotal": 312, "hp": 65, "atk": 92, "def": 85, "spd": 70, "stage": 2, "nextForm": "Kingambit", "evoTrigger": 10},
  {"id": 626, "name": "Bouffalant", "type": "Normal", "secondType": "", "BaseTotal": 320, "hp": 95, "atk": 75, "def": 95, "spd": 55, "stage": 1, "nextForm": null},
  {"id": 627, "name": "Rufflet", "type": "Normal", "secondType": "Voador", "BaseTotal": 240, "hp": 70, "atk": 60, "def": 50, "spd": 60, "stage": 1, "nextForm": "Braviary", "evoTrigger": 8},
  {"id": 628, "name": "Braviary", "type": "Normal", "secondType": "Voador", "BaseTotal": 345, "hp": 100, "atk": 90, "def": 75, "spd": 80, "stage": 2, "nextForm": null},
  {"id": 629, "name": "Vullaby", "type": "Noturno", "secondType": "Voador", "BaseTotal": 250, "hp": 70, "atk": 50, "def": 70, "spd": 60, "stage": 1, "nextForm": "Mandibuzz", "evoTrigger": 8},
  {"id": 630, "name": "Mandibuzz", "type": "Noturno", "secondType": "Voador", "BaseTotal": 350, "hp": 110, "atk": 60, "def": 100, "spd": 80, "stage": 2, "nextForm": null},
  {"id": 631, "name": "Heatmor", "type": "Fogo", "secondType": "", "BaseTotal": 317, "hp": 85, "atk": 101, "def": 66, "spd": 65, "stage": 1, "nextForm": null},
  {"id": 632, "name": "Durant", "type": "Inseto", "secondType": "Aço", "BaseTotal": 325, "hp": 58, "atk": 78, "def": 80, "spd": 109, "stage": 1, "nextForm": null},
  {"id": 633, "name": "Deino", "type": "Noturno", "secondType": "Dragão", "BaseTotal": 195, "hp": 52, "atk": 55, "def": 50, "spd": 38, "stage": 1, "nextForm": "Zweilous", "evoTrigger": 5},
  {"id": 634, "name": "Zweilous", "type": "Noturno", "secondType": "Dragão", "BaseTotal": 275, "hp": 72, "atk": 75, "def": 70, "spd": 58, "stage": 2, "nextForm": "Hydreigon", "evoTrigger": 10},
  {"id": 635, "name": "Hydreigon", "type": "Noturno", "secondType": "Dragão", "BaseTotal": 395, "hp": 92, "atk": 115, "def": 90, "spd": 98, "stage": 3, "nextForm": null},
  {"id": 636, "name": "Larvesta", "type": "Inseto", "secondType": "Fogo", "BaseTotal": 238, "hp": 55, "atk": 68, "def": 55, "spd": 60, "stage": 1, "nextForm": "Volcarona", "evoTrigger": 8},
  {"id": 637, "name": "Volcarona", "type": "Inseto", "secondType": "Fogo", "BaseTotal": 368, "hp": 85, "atk": 98, "def": 85, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 638, "name": "Cobalion", "type": "Aço", "secondType": "Lutador", "BaseTotal": 389, "hp": 91, "atk": 90, "def": 100, "spd": 108, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 639, "name": "Terrakion", "type": "Pedra", "secondType": "Lutador", "BaseTotal": 389, "hp": 91, "atk": 100, "def": 90, "spd": 108, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 640, "name": "Virizion", "type": "Grama", "secondType": "Lutador", "BaseTotal": 389, "hp": 91, "atk": 90, "def": 100, "spd": 108, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 641, "name": "Tornadus", "type": "Voador", "secondType": "", "BaseTotal": 385, "hp": 79, "atk": 120, "def": 75, "spd": 111, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 642, "name": "Thundurus", "type": "Elétrico", "secondType": "Voador", "BaseTotal": 385, "hp": 79, "atk": 120, "def": 75, "spd": 111, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 643, "name": "Reshiram", "type": "Dragão", "secondType": "Fogo", "BaseTotal": 435, "hp": 100, "atk": 135, "def": 110, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 644, "name": "Zekrom", "type": "Dragão", "secondType": "Elétrico", "BaseTotal": 435, "hp": 100, "atk": 135, "def": 110, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 645, "name": "Landorus", "type": "Terra", "secondType": "Voador", "BaseTotal": 395, "hp": 89, "atk": 120, "def": 85, "spd": 101, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 646, "name": "Kyurem", "type": "Dragão", "secondType": "Gelo", "BaseTotal": 440, "hp": 125, "atk": 130, "def": 90, "spd": 95, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 647, "name": "Keldeo", "type": "Água", "secondType": "Lutador", "BaseTotal": 389, "hp": 91, "atk": 100, "def": 90, "spd": 108, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 648, "name": "Meloetta", "type": "Normal", "secondType": "Psíquico", "BaseTotal": 394, "hp": 100, "atk": 102, "def": 102, "spd": 90, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 649, "name": "Genesect", "type": "Inseto", "secondType": "Aço", "BaseTotal": 385, "hp": 71, "atk": 120, "def": 95, "spd": 99, "stage": 1, "nextForm": null, "isLegendary": true}
];
