import type { PokemonData } from '../types';

export const GEN6: PokemonData[] = [
  {"id": 650, "name": "Chespin", "type": "Grama", "secondType": "", "BaseTotal": 203, "hp": 56, "atk": 54, "def": 55, "spd": 38, "stage": 1, "nextForm": "Quilladin", "evoTrigger": 5},
  {"id": 651, "name": "Quilladin", "type": "Grama", "secondType": "", "BaseTotal": 261, "hp": 61, "atk": 67, "def": 76, "spd": 57, "stage": 2, "nextForm": "Chesnaught", "evoTrigger": 10},
  {"id": 652, "name": "Chesnaught", "type": "Grama", "secondType": "Lutador", "BaseTotal": 340, "hp": 88, "atk": 90, "def": 98, "spd": 64, "stage": 3, "nextForm": null},
  {"id": 653, "name": "Fennekin", "type": "Fogo", "secondType": "", "BaseTotal": 204, "hp": 40, "atk": 54, "def": 50, "spd": 60, "stage": 1, "nextForm": "Braixen", "evoTrigger": 5},
  {"id": 654, "name": "Braixen", "type": "Fogo", "secondType": "", "BaseTotal": 270, "hp": 59, "atk": 74, "def": 64, "spd": 73, "stage": 2, "nextForm": "Delphox", "evoTrigger": 10},
  {"id": 655, "name": "Delphox", "type": "Fogo", "secondType": "Psíquico", "BaseTotal": 357, "hp": 75, "atk": 92, "def": 86, "spd": 104, "stage": 3, "nextForm": null},
  {"id": 656, "name": "Froakie", "type": "Água", "secondType": "", "BaseTotal": 213, "hp": 41, "atk": 59, "def": 42, "spd": 71, "stage": 1, "nextForm": "Frogadier", "evoTrigger": 5},
  {"id": 657, "name": "Frogadier", "type": "Água", "secondType": "", "BaseTotal": 278, "hp": 54, "atk": 73, "def": 54, "spd": 97, "stage": 2, "nextForm": "Greninja", "evoTrigger": 10},
  {"id": 658, "name": "Greninja", "type": "Água", "secondType": "Noturno", "BaseTotal": 362, "hp": 72, "atk": 99, "def": 69, "spd": 122, "stage": 3, "nextForm": null},
  {"id": 659, "name": "Bunnelby", "type": "Normal", "secondType": "", "BaseTotal": 166, "hp": 38, "atk": 34, "def": 37, "spd": 57, "stage": 1, "nextForm": "Diggersby", "evoTrigger": 8},
  {"id": 660, "name": "Diggersby", "type": "Normal", "secondType": "Terra", "BaseTotal": 293, "hp": 85, "atk": 53, "def": 77, "spd": 78, "stage": 2, "nextForm": null},
  {"id": 661, "name": "Fletchling", "type": "Normal", "secondType": "Voador", "BaseTotal": 192, "hp": 45, "atk": 45, "def": 40, "spd": 62, "stage": 1, "nextForm": "Fletchinder", "evoTrigger": 5},
  {"id": 662, "name": "Fletchinder", "type": "Fogo", "secondType": "Voador", "BaseTotal": 264, "hp": 62, "atk": 64, "def": 54, "spd": 84, "stage": 2, "nextForm": "Talonflame", "evoTrigger": 10},
  {"id": 663, "name": "Talonflame", "type": "Fogo", "secondType": "Voador", "BaseTotal": 352, "hp": 78, "atk": 78, "def": 70, "spd": 126, "stage": 3, "nextForm": null},
  {"id": 664, "name": "Scatterbug", "type": "Inseto", "secondType": "", "BaseTotal": 136, "hp": 38, "atk": 31, "def": 32, "spd": 35, "stage": 1, "nextForm": "Spewpa", "evoTrigger": 5},
  {"id": 665, "name": "Spewpa", "type": "Inseto", "secondType": "", "BaseTotal": 143, "hp": 45, "atk": 24, "def": 45, "spd": 29, "stage": 2, "nextForm": "Vivillon", "evoTrigger": 10},
  {"id": 666, "name": "Vivillon", "type": "Inseto", "secondType": "Voador", "BaseTotal": 290, "hp": 80, "atk": 71, "def": 50, "spd": 89, "stage": 3, "nextForm": null},
  {"id": 667, "name": "Litleo", "type": "Fogo", "secondType": "Normal", "BaseTotal": 252, "hp": 62, "atk": 62, "def": 56, "spd": 72, "stage": 1, "nextForm": "Pyroar", "evoTrigger": 8},
  {"id": 668, "name": "Pyroar", "type": "Fogo", "secondType": "Normal", "BaseTotal": 349, "hp": 86, "atk": 88, "def": 69, "spd": 106, "stage": 2, "nextForm": null},
  {"id": 669, "name": "Flabébé", "type": "Fada", "secondType": "", "BaseTotal": 195, "hp": 44, "atk": 50, "def": 59, "spd": 42, "stage": 1, "nextForm": "Floette", "evoTrigger": 5},
  {"id": 670, "name": "Floette", "type": "Fada", "secondType": "", "BaseTotal": 238, "hp": 54, "atk": 60, "def": 72, "spd": 52, "stage": 2, "nextForm": "Florges", "evoTrigger": 10},
  {"id": 671, "name": "Florges", "type": "Fada", "secondType": "", "BaseTotal": 352, "hp": 78, "atk": 88, "def": 111, "spd": 75, "stage": 3, "nextForm": null},
  {"id": 672, "name": "Skiddo", "type": "Grama", "secondType": "", "BaseTotal": 234, "hp": 66, "atk": 64, "def": 52, "spd": 52, "stage": 1, "nextForm": "Gogoat", "evoTrigger": 8},
  {"id": 673, "name": "Gogoat", "type": "Grama", "secondType": "", "BaseTotal": 361, "hp": 123, "atk": 98, "def": 72, "spd": 68, "stage": 2, "nextForm": null},
  {"id": 674, "name": "Pancham", "type": "Lutador", "secondType": "", "BaseTotal": 229, "hp": 67, "atk": 64, "def": 55, "spd": 43, "stage": 1, "nextForm": "Pangoro", "evoTrigger": 8},
  {"id": 675, "name": "Pangoro", "type": "Lutador", "secondType": "Noturno", "BaseTotal": 323, "hp": 95, "atk": 96, "def": 74, "spd": 58, "stage": 2, "nextForm": null},
  {"id": 676, "name": "Furfrou", "type": "Normal", "secondType": "", "BaseTotal": 324, "hp": 75, "atk": 72, "def": 75, "spd": 102, "stage": 1, "nextForm": null},
  {"id": 677, "name": "Espurr", "type": "Psíquico", "secondType": "", "BaseTotal": 243, "hp": 62, "atk": 56, "def": 57, "spd": 68, "stage": 1, "nextForm": "Meowstic", "evoTrigger": 8},
  {"id": 678, "name": "Meowstic", "type": "Psíquico", "secondType": "", "BaseTotal": 322, "hp": 74, "atk": 66, "def": 78, "spd": 104, "stage": 2, "nextForm": null},
  {"id": 679, "name": "Honedge", "type": "Aço", "secondType": "Fantasma", "BaseTotal": 199, "hp": 45, "atk": 58, "def": 68, "spd": 28, "stage": 1, "nextForm": "Doublade", "evoTrigger": 5},
  {"id": 680, "name": "Doublade", "type": "Aço", "secondType": "Fantasma", "BaseTotal": 272, "hp": 59, "atk": 78, "def": 100, "spd": 35, "stage": 2, "nextForm": "Aegislash", "evoTrigger": 10},
  {"id": 681, "name": "Aegislash", "type": "Aço", "secondType": "Fantasma", "BaseTotal": 320, "hp": 60, "atk": 150, "def": 50, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 682, "name": "Spritzee", "type": "Fada", "secondType": "", "BaseTotal": 221, "hp": 78, "atk": 58, "def": 62, "spd": 23, "stage": 1, "nextForm": "Aromatisse", "evoTrigger": 8},
  {"id": 683, "name": "Aromatisse", "type": "Fada", "secondType": "", "BaseTotal": 296, "hp": 101, "atk": 86, "def": 80, "spd": 29, "stage": 2, "nextForm": null},
  {"id": 684, "name": "Swirlix", "type": "Fada", "secondType": "", "BaseTotal": 227, "hp": 62, "atk": 54, "def": 62, "spd": 49, "stage": 1, "nextForm": "Slurpuff", "evoTrigger": 8},
  {"id": 685, "name": "Slurpuff", "type": "Fada", "secondType": "", "BaseTotal": 316, "hp": 82, "atk": 82, "def": 80, "spd": 72, "stage": 2, "nextForm": null},
  {"id": 686, "name": "Inkay", "type": "Noturno", "secondType": "Psíquico", "BaseTotal": 194, "hp": 53, "atk": 46, "def": 50, "spd": 45, "stage": 1, "nextForm": "Malamar", "evoTrigger": 8},
  {"id": 687, "name": "Malamar", "type": "Noturno", "secondType": "Psíquico", "BaseTotal": 321, "hp": 86, "atk": 80, "def": 82, "spd": 73, "stage": 2, "nextForm": null},
  {"id": 688, "name": "Binacle", "type": "Pedra", "secondType": "Água", "BaseTotal": 200, "hp": 42, "atk": 46, "def": 62, "spd": 50, "stage": 1, "nextForm": "Barbaracle", "evoTrigger": 8},
  {"id": 689, "name": "Barbaracle", "type": "Pedra", "secondType": "Água", "BaseTotal": 320, "hp": 72, "atk": 80, "def": 100, "spd": 68, "stage": 2, "nextForm": null},
  {"id": 690, "name": "Skrelp", "type": "Veneno", "secondType": "Água", "BaseTotal": 200, "hp": 50, "atk": 60, "def": 60, "spd": 30, "stage": 1, "nextForm": "Dragalge", "evoTrigger": 8},
  {"id": 691, "name": "Dragalge", "type": "Veneno", "secondType": "Dragão", "BaseTotal": 301, "hp": 65, "atk": 86, "def": 106, "spd": 44, "stage": 2, "nextForm": null},
  {"id": 692, "name": "Clauncher", "type": "Água", "secondType": "", "BaseTotal": 212, "hp": 50, "atk": 56, "def": 62, "spd": 44, "stage": 1, "nextForm": "Clawitzer", "evoTrigger": 8},
  {"id": 693, "name": "Clawitzer", "type": "Água", "secondType": "", "BaseTotal": 314, "hp": 71, "atk": 96, "def": 88, "spd": 59, "stage": 2, "nextForm": null},
  {"id": 694, "name": "Helioptile", "type": "Elétrico", "secondType": "Normal", "BaseTotal": 202, "hp": 44, "atk": 50, "def": 38, "spd": 70, "stage": 1, "nextForm": "Heliolisk", "evoTrigger": 8},
  {"id": 695, "name": "Heliolisk", "type": "Elétrico", "secondType": "Normal", "BaseTotal": 326, "hp": 62, "atk": 82, "def": 73, "spd": 109, "stage": 2, "nextForm": null},
  {"id": 696, "name": "Tyrunt", "type": "Pedra", "secondType": "Dragão", "BaseTotal": 234, "hp": 58, "atk": 67, "def": 61, "spd": 48, "stage": 1, "nextForm": "Tyrantrum", "evoTrigger": 8},
  {"id": 697, "name": "Tyrantrum", "type": "Pedra", "secondType": "Dragão", "BaseTotal": 337, "hp": 82, "atk": 95, "def": 89, "spd": 71, "stage": 2, "nextForm": null},
  {"id": 698, "name": "Amaura", "type": "Pedra", "secondType": "Gelo", "BaseTotal": 242, "hp": 77, "atk": 63, "def": 56, "spd": 46, "stage": 1, "nextForm": "Aurorus", "evoTrigger": 8},
  {"id": 699, "name": "Aurorus", "type": "Pedra", "secondType": "Gelo", "BaseTotal": 351, "hp": 123, "atk": 88, "def": 82, "spd": 58, "stage": 2, "nextForm": null},
  {"id": 700, "name": "Sylveon", "type": "Fada", "secondType": "", "BaseTotal": 341, "hp": 95, "atk": 88, "def": 98, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 701, "name": "Hawlucha", "type": "Lutador", "secondType": "Voador", "BaseTotal": 348, "hp": 78, "atk": 83, "def": 69, "spd": 118, "stage": 1, "nextForm": null},
  {"id": 702, "name": "Dedenne", "type": "Elétrico", "secondType": "Fada", "BaseTotal": 300, "hp": 67, "atk": 70, "def": 62, "spd": 101, "stage": 1, "nextForm": null},
  {"id": 703, "name": "Carbink", "type": "Pedra", "secondType": "Fada", "BaseTotal": 300, "hp": 50, "atk": 50, "def": 150, "spd": 50, "stage": 1, "nextForm": null},
  {"id": 704, "name": "Goomy", "type": "Dragão", "secondType": "", "BaseTotal": 192, "hp": 45, "atk": 52, "def": 55, "spd": 40, "stage": 1, "nextForm": "Sliggoo", "evoTrigger": 5},
  {"id": 705, "name": "Sliggoo", "type": "Dragão", "secondType": "", "BaseTotal": 290, "hp": 68, "atk": 79, "def": 83, "spd": 60, "stage": 2, "nextForm": "Goodra", "evoTrigger": 10},
  {"id": 706, "name": "Goodra", "type": "Dragão", "secondType": "", "BaseTotal": 385, "hp": 90, "atk": 105, "def": 110, "spd": 80, "stage": 3, "nextForm": null},
  {"id": 707, "name": "Klefki", "type": "Aço", "secondType": "Fada", "BaseTotal": 301, "hp": 57, "atk": 80, "def": 89, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 708, "name": "Phantump", "type": "Fantasma", "secondType": "Grama", "BaseTotal": 195, "hp": 43, "atk": 60, "def": 54, "spd": 38, "stage": 1, "nextForm": "Trevenant", "evoTrigger": 8},
  {"id": 709, "name": "Trevenant", "type": "Fantasma", "secondType": "Grama", "BaseTotal": 308, "hp": 85, "atk": 88, "def": 79, "spd": 56, "stage": 2, "nextForm": null},
  {"id": 710, "name": "Pumpkaboo", "type": "Fantasma", "secondType": "Grama", "BaseTotal": 217, "hp": 49, "atk": 55, "def": 62, "spd": 51, "stage": 1, "nextForm": "Gourgeist", "evoTrigger": 8},
  {"id": 711, "name": "Gourgeist", "type": "Fantasma", "secondType": "Grama", "BaseTotal": 321, "hp": 65, "atk": 74, "def": 98, "spd": 84, "stage": 2, "nextForm": null},
  {"id": 712, "name": "Bergmite", "type": "Gelo", "secondType": "", "BaseTotal": 193, "hp": 55, "atk": 50, "def": 60, "spd": 28, "stage": 1, "nextForm": "Avalugg", "evoTrigger": 8},
  {"id": 713, "name": "Avalugg", "type": "Gelo", "secondType": "", "BaseTotal": 318, "hp": 95, "atk": 80, "def": 115, "spd": 28, "stage": 2, "nextForm": null},
  {"id": 714, "name": "Noibat", "type": "Voador", "secondType": "Dragão", "BaseTotal": 171, "hp": 40, "atk": 38, "def": 38, "spd": 55, "stage": 1, "nextForm": "Noivern", "evoTrigger": 8},
  {"id": 715, "name": "Noivern", "type": "Voador", "secondType": "Dragão", "BaseTotal": 372, "hp": 85, "atk": 84, "def": 80, "spd": 123, "stage": 2, "nextForm": null},
  {"id": 716, "name": "Xerneas", "type": "Fada", "secondType": "", "BaseTotal": 452, "hp": 126, "atk": 131, "def": 96, "spd": 99, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 717, "name": "Yveltal", "type": "Noturno", "secondType": "Voador", "BaseTotal": 452, "hp": 126, "atk": 131, "def": 96, "spd": 99, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 718, "name": "Zygarde", "type": "Dragão", "secondType": "Terra", "BaseTotal": 401, "hp": 108, "atk": 90, "def": 108, "spd": 95, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 719, "name": "Diancie", "type": "Pedra", "secondType": "Fada", "BaseTotal": 350, "hp": 50, "atk": 100, "def": 150, "spd": 50, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 720, "name": "Hoopa", "type": "Psíquico", "secondType": "Fantasma", "BaseTotal": 375, "hp": 80, "atk": 130, "def": 95, "spd": 70, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 721, "name": "Volcanion", "type": "Fogo", "secondType": "Água", "BaseTotal": 375, "hp": 80, "atk": 120, "def": 105, "spd": 70, "stage": 1, "nextForm": null, "isLegendary": true}
];
