import type { PokemonData } from '../types';

export const GEN7: PokemonData[] = [
  {"id": 722, "name": "Rowlet", "type": "Grama", "secondType": "Voador", "BaseTotal": 214, "hp": 68, "atk": 52, "def": 52, "spd": 42, "stage": 1, "nextForm": "Dartrix", "evoTrigger": 5},
  {"id": 723, "name": "Dartrix", "type": "Grama", "secondType": "Voador", "BaseTotal": 274, "hp": 78, "atk": 72, "def": 72, "spd": 52, "stage": 2, "nextForm": "Decidueye", "evoTrigger": 10},
  {"id": 724, "name": "Decidueye", "type": "Grama", "secondType": "Fantasma", "BaseTotal": 340, "hp": 78, "atk": 104, "def": 88, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 725, "name": "Litten", "type": "Fogo", "secondType": "", "BaseTotal": 217, "hp": 45, "atk": 62, "def": 40, "spd": 70, "stage": 1, "nextForm": "Torracat", "evoTrigger": 5},
  {"id": 726, "name": "Torracat", "type": "Fogo", "secondType": "", "BaseTotal": 287, "hp": 65, "atk": 82, "def": 50, "spd": 90, "stage": 2, "nextForm": "Incineroar", "evoTrigger": 10},
  {"id": 727, "name": "Incineroar", "type": "Fogo", "secondType": "Noturno", "BaseTotal": 343, "hp": 95, "atk": 98, "def": 90, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 728, "name": "Popplio", "type": "Água", "secondType": "", "BaseTotal": 205, "hp": 50, "atk": 60, "def": 55, "spd": 40, "stage": 1, "nextForm": "Brionne", "evoTrigger": 5},
  {"id": 729, "name": "Brionne", "type": "Água", "secondType": "", "BaseTotal": 265, "hp": 60, "atk": 80, "def": 75, "spd": 50, "stage": 2, "nextForm": "Primarina", "evoTrigger": 10},
  {"id": 730, "name": "Primarina", "type": "Água", "secondType": "Fada", "BaseTotal": 335, "hp": 80, "atk": 100, "def": 95, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 731, "name": "Pikipek", "type": "Normal", "secondType": "Voador", "BaseTotal": 182, "hp": 35, "atk": 52, "def": 30, "spd": 65, "stage": 1, "nextForm": "Trumbeak", "evoTrigger": 5},
  {"id": 732, "name": "Trumbeak", "type": "Normal", "secondType": "Voador", "BaseTotal": 242, "hp": 55, "atk": 62, "def": 50, "spd": 75, "stage": 2, "nextForm": "Toucannon", "evoTrigger": 10},
  {"id": 733, "name": "Toucannon", "type": "Normal", "secondType": "Voador", "BaseTotal": 313, "hp": 80, "atk": 98, "def": 75, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 734, "name": "Yungoos", "type": "Normal", "secondType": "", "BaseTotal": 173, "hp": 48, "atk": 50, "def": 30, "spd": 45, "stage": 1, "nextForm": "Gumshoos", "evoTrigger": 8},
  {"id": 735, "name": "Gumshoos", "type": "Normal", "secondType": "", "BaseTotal": 275, "hp": 88, "atk": 82, "def": 60, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 736, "name": "Grubbin", "type": "Inseto", "secondType": "", "BaseTotal": 196, "hp": 47, "atk": 58, "def": 45, "spd": 46, "stage": 1, "nextForm": "Charjabug", "evoTrigger": 5},
  {"id": 737, "name": "Charjabug", "type": "Inseto", "secondType": "Elétrico", "BaseTotal": 246, "hp": 57, "atk": 68, "def": 85, "spd": 36, "stage": 2, "nextForm": "Vikavolt", "evoTrigger": 10},
  {"id": 738, "name": "Vikavolt", "type": "Inseto", "secondType": "Elétrico", "BaseTotal": 310, "hp": 77, "atk": 108, "def": 82, "spd": 43, "stage": 3, "nextForm": null},
  {"id": 739, "name": "Crabrawler", "type": "Lutador", "secondType": "", "BaseTotal": 224, "hp": 47, "atk": 62, "def": 52, "spd": 63, "stage": 1, "nextForm": "Crabominable", "evoTrigger": 8},
  {"id": 740, "name": "Crabominable", "type": "Lutador", "secondType": "Gelo", "BaseTotal": 309, "hp": 97, "atk": 97, "def": 72, "spd": 43, "stage": 2, "nextForm": null},
  {"id": 741, "name": "Oricorio", "type": "Fogo", "secondType": "Voador", "BaseTotal": 322, "hp": 75, "atk": 84, "def": 70, "spd": 93, "stage": 1, "nextForm": null},
  {"id": 742, "name": "Cutiefly", "type": "Inseto", "secondType": "Fada", "BaseTotal": 214, "hp": 40, "atk": 50, "def": 40, "spd": 84, "stage": 1, "nextForm": "Ribombee", "evoTrigger": 8},
  {"id": 743, "name": "Ribombee", "type": "Inseto", "secondType": "Fada", "BaseTotal": 324, "hp": 60, "atk": 75, "def": 65, "spd": 124, "stage": 2, "nextForm": null},
  {"id": 744, "name": "Rockruff", "type": "Pedra", "secondType": "", "BaseTotal": 193, "hp": 45, "atk": 48, "def": 40, "spd": 60, "stage": 1, "nextForm": "Lycanroc", "evoTrigger": 8},
  {"id": 745, "name": "Lycanroc", "type": "Pedra", "secondType": "", "BaseTotal": 337, "hp": 75, "atk": 85, "def": 65, "spd": 112, "stage": 2, "nextForm": null},
  {"id": 746, "name": "Wishiwashi", "type": "Água", "secondType": "", "BaseTotal": 129, "hp": 45, "atk": 22, "def": 22, "spd": 40, "stage": 1, "nextForm": null},
  {"id": 747, "name": "Mareanie", "type": "Veneno", "secondType": "Água", "BaseTotal": 200, "hp": 50, "atk": 48, "def": 57, "spd": 45, "stage": 1, "nextForm": "Toxapex", "evoTrigger": 8},
  {"id": 748, "name": "Toxapex", "type": "Veneno", "secondType": "Água", "BaseTotal": 290, "hp": 50, "atk": 58, "def": 147, "spd": 35, "stage": 2, "nextForm": null},
  {"id": 749, "name": "Mudbray", "type": "Terra", "secondType": "", "BaseTotal": 249, "hp": 70, "atk": 72, "def": 62, "spd": 45, "stage": 1, "nextForm": "Mudsdale", "evoTrigger": 8},
  {"id": 750, "name": "Mudsdale", "type": "Terra", "secondType": "", "BaseTotal": 317, "hp": 100, "atk": 90, "def": 92, "spd": 35, "stage": 2, "nextForm": null},
  {"id": 751, "name": "Dewpider", "type": "Água", "secondType": "Inseto", "BaseTotal": 167, "hp": 38, "atk": 40, "def": 62, "spd": 27, "stage": 1, "nextForm": "Araquanid", "evoTrigger": 8},
  {"id": 752, "name": "Araquanid", "type": "Água", "secondType": "Inseto", "BaseTotal": 282, "hp": 68, "atk": 60, "def": 112, "spd": 42, "stage": 2, "nextForm": null},
  {"id": 753, "name": "Fomantis", "type": "Grama", "secondType": "", "BaseTotal": 162, "hp": 40, "atk": 52, "def": 35, "spd": 35, "stage": 1, "nextForm": "Lurantis", "evoTrigger": 8},
  {"id": 754, "name": "Lurantis", "type": "Grama", "secondType": "", "BaseTotal": 297, "hp": 70, "atk": 92, "def": 90, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 755, "name": "Morelull", "type": "Grama", "secondType": "Fada", "BaseTotal": 170, "hp": 40, "atk": 50, "def": 65, "spd": 15, "stage": 1, "nextForm": "Shiinotic", "evoTrigger": 8},
  {"id": 756, "name": "Shiinotic", "type": "Grama", "secondType": "Fada", "BaseTotal": 248, "hp": 60, "atk": 68, "def": 90, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 757, "name": "Salandit", "type": "Veneno", "secondType": "Fogo", "BaseTotal": 223, "hp": 48, "atk": 58, "def": 40, "spd": 77, "stage": 1, "nextForm": "Salazzle", "evoTrigger": 8},
  {"id": 758, "name": "Salazzle", "type": "Veneno", "secondType": "Fogo", "BaseTotal": 333, "hp": 68, "atk": 88, "def": 60, "spd": 117, "stage": 2, "nextForm": null},
  {"id": 759, "name": "Stufful", "type": "Normal", "secondType": "Lutador", "BaseTotal": 230, "hp": 70, "atk": 60, "def": 50, "spd": 50, "stage": 1, "nextForm": "Bewear", "evoTrigger": 8},
  {"id": 760, "name": "Bewear", "type": "Normal", "secondType": "Lutador", "BaseTotal": 340, "hp": 120, "atk": 90, "def": 70, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 761, "name": "Bounsweet", "type": "Grama", "secondType": "", "BaseTotal": 142, "hp": 42, "atk": 30, "def": 38, "spd": 32, "stage": 1, "nextForm": "Steenee", "evoTrigger": 5},
  {"id": 762, "name": "Steenee", "type": "Grama", "secondType": "", "BaseTotal": 202, "hp": 52, "atk": 40, "def": 48, "spd": 62, "stage": 2, "nextForm": "Tsareena", "evoTrigger": 10},
  {"id": 763, "name": "Tsareena", "type": "Grama", "secondType": "", "BaseTotal": 327, "hp": 72, "atk": 85, "def": 98, "spd": 72, "stage": 3, "nextForm": null},
  {"id": 764, "name": "Comfey", "type": "Fada", "secondType": "", "BaseTotal": 318, "hp": 51, "atk": 67, "def": 100, "spd": 100, "stage": 1, "nextForm": null},
  {"id": 765, "name": "Oranguru", "type": "Normal", "secondType": "Psíquico", "BaseTotal": 320, "hp": 90, "atk": 75, "def": 95, "spd": 60, "stage": 1, "nextForm": null},
  {"id": 766, "name": "Passimian", "type": "Lutador", "secondType": "", "BaseTotal": 335, "hp": 100, "atk": 80, "def": 75, "spd": 80, "stage": 1, "nextForm": null},
  {"id": 767, "name": "Wimpod", "type": "Inseto", "secondType": "Água", "BaseTotal": 168, "hp": 25, "atk": 28, "def": 35, "spd": 80, "stage": 1, "nextForm": "Golisopod", "evoTrigger": 8},
  {"id": 768, "name": "Golisopod", "type": "Inseto", "secondType": "Água", "BaseTotal": 322, "hp": 75, "atk": 92, "def": 115, "spd": 40, "stage": 2, "nextForm": null},
  {"id": 769, "name": "Sandygast", "type": "Fantasma", "secondType": "Terra", "BaseTotal": 194, "hp": 55, "atk": 62, "def": 62, "spd": 15, "stage": 1, "nextForm": "Palossand", "evoTrigger": 8},
  {"id": 770, "name": "Palossand", "type": "Fantasma", "secondType": "Terra", "BaseTotal": 300, "hp": 85, "atk": 88, "def": 92, "spd": 35, "stage": 2, "nextForm": null},
  {"id": 771, "name": "Pyukumuku", "type": "Água", "secondType": "", "BaseTotal": 235, "hp": 55, "atk": 45, "def": 130, "spd": 5, "stage": 1, "nextForm": null},
  {"id": 772, "name": "Type: Null", "type": "Normal", "secondType": "", "BaseTotal": 344, "hp": 95, "atk": 95, "def": 95, "spd": 59, "stage": 1, "nextForm": "Silvally", "evoTrigger": 8},
  {"id": 773, "name": "Silvally", "type": "Normal", "secondType": "", "BaseTotal": 380, "hp": 95, "atk": 95, "def": 95, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 774, "name": "Minior", "type": "Pedra", "secondType": "Voador", "BaseTotal": 280, "hp": 60, "atk": 60, "def": 100, "spd": 60, "stage": 1, "nextForm": null},
  {"id": 775, "name": "Komala", "type": "Normal", "secondType": "", "BaseTotal": 305, "hp": 65, "atk": 95, "def": 80, "spd": 65, "stage": 1, "nextForm": null},
  {"id": 776, "name": "Turtonator", "type": "Fogo", "secondType": "Dragão", "BaseTotal": 290, "hp": 60, "atk": 84, "def": 110, "spd": 36, "stage": 1, "nextForm": null},
  {"id": 777, "name": "Togedemaru", "type": "Elétrico", "secondType": "Aço", "BaseTotal": 298, "hp": 65, "atk": 69, "def": 68, "spd": 96, "stage": 1, "nextForm": null},
  {"id": 778, "name": "Mimikyu", "type": "Fantasma", "secondType": "Fada", "BaseTotal": 313, "hp": 55, "atk": 70, "def": 92, "spd": 96, "stage": 1, "nextForm": null},
  {"id": 779, "name": "Bruxish", "type": "Água", "secondType": "Psíquico", "BaseTotal": 318, "hp": 68, "atk": 88, "def": 70, "spd": 92, "stage": 1, "nextForm": null},
  {"id": 780, "name": "Drampa", "type": "Normal", "secondType": "Dragão", "BaseTotal": 300, "hp": 78, "atk": 98, "def": 88, "spd": 36, "stage": 1, "nextForm": null},
  {"id": 781, "name": "Dhelmise", "type": "Fantasma", "secondType": "Grama", "BaseTotal": 313, "hp": 70, "atk": 108, "def": 95, "spd": 40, "stage": 1, "nextForm": null},
  {"id": 782, "name": "Jangmo-o", "type": "Dragão", "secondType": "", "BaseTotal": 195, "hp": 45, "atk": 50, "def": 55, "spd": 45, "stage": 1, "nextForm": "Hakamo-o", "evoTrigger": 5},
  {"id": 783, "name": "Hakamo-o", "type": "Dragão", "secondType": "Lutador", "BaseTotal": 270, "hp": 55, "atk": 70, "def": 80, "spd": 65, "stage": 2, "nextForm": "Kommo-o", "evoTrigger": 10},
  {"id": 784, "name": "Kommo-o", "type": "Dragão", "secondType": "Lutador", "BaseTotal": 380, "hp": 75, "atk": 105, "def": 115, "spd": 85, "stage": 3, "nextForm": null},
  {"id": 785, "name": "Tapu Koko", "type": "Elétrico", "secondType": "Fada", "BaseTotal": 385, "hp": 70, "atk": 105, "def": 80, "spd": 130, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 786, "name": "Tapu Lele", "type": "Psíquico", "secondType": "Fada", "BaseTotal": 368, "hp": 70, "atk": 108, "def": 95, "spd": 95, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 787, "name": "Tapu Bulu", "type": "Grama", "secondType": "Fada", "BaseTotal": 358, "hp": 70, "atk": 108, "def": 105, "spd": 75, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 788, "name": "Tapu Fini", "type": "Água", "secondType": "Fada", "BaseTotal": 362, "hp": 70, "atk": 85, "def": 122, "spd": 85, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 789, "name": "Cosmog", "type": "Psíquico", "secondType": "", "BaseTotal": 140, "hp": 43, "atk": 29, "def": 31, "spd": 37, "stage": 1, "nextForm": "Cosmoem", "evoTrigger": 5, "isLegendary": true},
  {"id": 790, "name": "Cosmoem", "type": "Psíquico", "secondType": "", "BaseTotal": 240, "hp": 43, "atk": 29, "def": 131, "spd": 37, "stage": 2, "nextForm": "Solgaleo", "evoTrigger": 10, "isLegendary": true},
  {"id": 791, "name": "Solgaleo", "type": "Psíquico", "secondType": "Aço", "BaseTotal": 457, "hp": 137, "atk": 125, "def": 98, "spd": 97, "stage": 3, "nextForm": null, "isLegendary": true},
  {"id": 792, "name": "Lunala", "type": "Psíquico", "secondType": "Fantasma", "BaseTotal": 457, "hp": 137, "atk": 125, "def": 98, "spd": 97, "stage": 3, "nextForm": null, "isLegendary": true},
  {"id": 793, "name": "Nihilego", "type": "Pedra", "secondType": "Veneno", "BaseTotal": 391, "hp": 109, "atk": 90, "def": 89, "spd": 103, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 794, "name": "Buzzwole", "type": "Inseto", "secondType": "Lutador", "BaseTotal": 378, "hp": 107, "atk": 96, "def": 96, "spd": 79, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 795, "name": "Pheromosa", "type": "Inseto", "secondType": "Lutador", "BaseTotal": 396, "hp": 71, "atk": 137, "def": 37, "spd": 151, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 796, "name": "Xurkitree", "type": "Elétrico", "secondType": "", "BaseTotal": 368, "hp": 83, "atk": 131, "def": 71, "spd": 83, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 797, "name": "Celesteela", "type": "Aço", "secondType": "Voador", "BaseTotal": 364, "hp": 97, "atk": 104, "def": 102, "spd": 61, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 798, "name": "Kartana", "type": "Grama", "secondType": "Aço", "BaseTotal": 369, "hp": 59, "atk": 120, "def": 81, "spd": 109, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 799, "name": "Guzzlord", "type": "Noturno", "secondType": "Dragão", "BaseTotal": 418, "hp": 223, "atk": 99, "def": 53, "spd": 43, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 800, "name": "Necrozma", "type": "Psíquico", "secondType": "", "BaseTotal": 388, "hp": 97, "atk": 117, "def": 95, "spd": 79, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 801, "name": "Magearna", "type": "Aço", "secondType": "Fada", "BaseTotal": 372, "hp": 80, "atk": 112, "def": 115, "spd": 65, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 802, "name": "Marshadow", "type": "Lutador", "secondType": "Fantasma", "BaseTotal": 408, "hp": 90, "atk": 108, "def": 85, "spd": 125, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 803, "name": "Poipole", "type": "Veneno", "secondType": "", "BaseTotal": 280, "hp": 67, "atk": 73, "def": 67, "spd": 73, "stage": 1, "nextForm": "Naganadel", "evoTrigger": 8, "isLegendary": true},
  {"id": 804, "name": "Naganadel", "type": "Veneno", "secondType": "Dragão", "BaseTotal": 367, "hp": 73, "atk": 100, "def": 73, "spd": 121, "stage": 2, "nextForm": null, "isLegendary": true},
  {"id": 805, "name": "Stakataka", "type": "Pedra", "secondType": "Aço", "BaseTotal": 322, "hp": 61, "atk": 92, "def": 156, "spd": 13, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 806, "name": "Blacephalon", "type": "Fogo", "secondType": "Fantasma", "BaseTotal": 365, "hp": 53, "atk": 139, "def": 66, "spd": 107, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 807, "name": "Zeraora", "type": "Elétrico", "secondType": "", "BaseTotal": 416, "hp": 88, "atk": 107, "def": 78, "spd": 143, "stage": 1, "nextForm": null, "isLegendary": true}
];
