import type { PokemonData } from '../types';

export const GEN8: PokemonData[] = [
  {"id": 810, "name": "Grookey", "type": "Grama", "secondType": "", "BaseTotal": 212, "hp": 50, "atk": 52, "def": 45, "spd": 65, "stage": 1, "nextForm": "Thwackey", "evoTrigger": 5},
  {"id": 811, "name": "Thwackey", "type": "Grama", "secondType": "", "BaseTotal": 285, "hp": 70, "atk": 70, "def": 65, "spd": 80, "stage": 2, "nextForm": "Rillaboom", "evoTrigger": 10},
  {"id": 812, "name": "Rillaboom", "type": "Grama", "secondType": "", "BaseTotal": 357, "hp": 100, "atk": 92, "def": 80, "spd": 85, "stage": 3, "nextForm": null},
  {"id": 813, "name": "Scorbunny", "type": "Fogo", "secondType": "", "BaseTotal": 215, "hp": 50, "atk": 56, "def": 40, "spd": 69, "stage": 1, "nextForm": "Raboot", "evoTrigger": 5},
  {"id": 814, "name": "Raboot", "type": "Fogo", "secondType": "", "BaseTotal": 289, "hp": 65, "atk": 70, "def": 60, "spd": 94, "stage": 2, "nextForm": "Cinderace", "evoTrigger": 10},
  {"id": 815, "name": "Cinderace", "type": "Fogo", "secondType": "", "BaseTotal": 364, "hp": 80, "atk": 90, "def": 75, "spd": 119, "stage": 3, "nextForm": null},
  {"id": 816, "name": "Sobble", "type": "Água", "secondType": "", "BaseTotal": 215, "hp": 50, "atk": 55, "def": 40, "spd": 70, "stage": 1, "nextForm": "Drizzile", "evoTrigger": 5},
  {"id": 817, "name": "Drizzile", "type": "Água", "secondType": "", "BaseTotal": 288, "hp": 65, "atk": 78, "def": 55, "spd": 90, "stage": 2, "nextForm": "Inteleon", "evoTrigger": 10},
  {"id": 818, "name": "Inteleon", "type": "Água", "secondType": "", "BaseTotal": 360, "hp": 70, "atk": 105, "def": 65, "spd": 120, "stage": 3, "nextForm": null},
  {"id": 819, "name": "Skwovet", "type": "Normal", "secondType": "", "BaseTotal": 185, "hp": 70, "atk": 45, "def": 45, "spd": 25, "stage": 1, "nextForm": "Greedent", "evoTrigger": 8},
  {"id": 820, "name": "Greedent", "type": "Normal", "secondType": "", "BaseTotal": 300, "hp": 120, "atk": 75, "def": 85, "spd": 20, "stage": 2, "nextForm": null},
  {"id": 821, "name": "Rookidee", "type": "Voador", "secondType": "", "BaseTotal": 170, "hp": 38, "atk": 40, "def": 35, "spd": 57, "stage": 1, "nextForm": "Corvisquire", "evoTrigger": 5},
  {"id": 822, "name": "Corvisquire", "type": "Voador", "secondType": "", "BaseTotal": 255, "hp": 68, "atk": 55, "def": 55, "spd": 77, "stage": 2, "nextForm": "Corviknight", "evoTrigger": 10},
  {"id": 823, "name": "Corviknight", "type": "Voador", "secondType": "Aço", "BaseTotal": 330, "hp": 98, "atk": 70, "def": 95, "spd": 67, "stage": 3, "nextForm": null},
  {"id": 824, "name": "Blipbug", "type": "Inseto", "secondType": "", "BaseTotal": 124, "hp": 25, "atk": 22, "def": 32, "spd": 45, "stage": 1, "nextForm": "Dottler", "evoTrigger": 5},
  {"id": 825, "name": "Dottler", "type": "Inseto", "secondType": "Psíquico", "BaseTotal": 207, "hp": 50, "atk": 42, "def": 85, "spd": 30, "stage": 2, "nextForm": "Orbeetle", "evoTrigger": 10},
  {"id": 826, "name": "Orbeetle", "type": "Inseto", "secondType": "Psíquico", "BaseTotal": 327, "hp": 60, "atk": 62, "def": 115, "spd": 90, "stage": 3, "nextForm": null},
  {"id": 827, "name": "Nickit", "type": "Noturno", "secondType": "", "BaseTotal": 168, "hp": 40, "atk": 38, "def": 40, "spd": 50, "stage": 1, "nextForm": "Thievul", "evoTrigger": 8},
  {"id": 828, "name": "Thievul", "type": "Noturno", "secondType": "", "BaseTotal": 307, "hp": 70, "atk": 72, "def": 75, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 829, "name": "Gossifleur", "type": "Grama", "secondType": "", "BaseTotal": 150, "hp": 40, "atk": 40, "def": 60, "spd": 10, "stage": 1, "nextForm": "Eldegoss", "evoTrigger": 8},
  {"id": 830, "name": "Eldegoss", "type": "Grama", "secondType": "", "BaseTotal": 290, "hp": 60, "atk": 65, "def": 105, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 831, "name": "Wooloo", "type": "Normal", "secondType": "", "BaseTotal": 180, "hp": 42, "atk": 40, "def": 50, "spd": 48, "stage": 1, "nextForm": "Dubwool", "evoTrigger": 8},
  {"id": 832, "name": "Dubwool", "type": "Normal", "secondType": "", "BaseTotal": 325, "hp": 72, "atk": 70, "def": 95, "spd": 88, "stage": 2, "nextForm": null},
  {"id": 833, "name": "Chewtle", "type": "Água", "secondType": "", "BaseTotal": 189, "hp": 50, "atk": 51, "def": 44, "spd": 44, "stage": 1, "nextForm": "Drednaw", "evoTrigger": 8},
  {"id": 834, "name": "Drednaw", "type": "Água", "secondType": "Pedra", "BaseTotal": 325, "hp": 90, "atk": 82, "def": 79, "spd": 74, "stage": 2, "nextForm": null},
  {"id": 835, "name": "Yamper", "type": "Elétrico", "secondType": "", "BaseTotal": 177, "hp": 59, "atk": 42, "def": 50, "spd": 26, "stage": 1, "nextForm": "Boltund", "evoTrigger": 8},
  {"id": 836, "name": "Boltund", "type": "Elétrico", "secondType": "", "BaseTotal": 340, "hp": 69, "atk": 90, "def": 60, "spd": 121, "stage": 2, "nextForm": null},
  {"id": 837, "name": "Rolycoly", "type": "Pedra", "secondType": "", "BaseTotal": 150, "hp": 30, "atk": 40, "def": 50, "spd": 30, "stage": 1, "nextForm": "Carkol", "evoTrigger": 5},
  {"id": 838, "name": "Carkol", "type": "Pedra", "secondType": "Fogo", "BaseTotal": 270, "hp": 80, "atk": 60, "def": 80, "spd": 50, "stage": 2, "nextForm": "Coalossal", "evoTrigger": 10},
  {"id": 839, "name": "Coalossal", "type": "Pedra", "secondType": "Fogo", "BaseTotal": 325, "hp": 110, "atk": 80, "def": 105, "spd": 30, "stage": 3, "nextForm": null},
  {"id": 840, "name": "Applin", "type": "Grama", "secondType": "Dragão", "BaseTotal": 160, "hp": 40, "atk": 40, "def": 60, "spd": 20, "stage": 1, "nextForm": null},
  {"id": 841, "name": "Flapple", "type": "Grama", "secondType": "Dragão", "BaseTotal": 312, "hp": 70, "atk": 102, "def": 70, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 842, "name": "Appletun", "type": "Grama", "secondType": "Dragão", "BaseTotal": 312, "hp": 110, "atk": 92, "def": 80, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 843, "name": "Silicobra", "type": "Terra", "secondType": "", "BaseTotal": 206, "hp": 52, "atk": 46, "def": 62, "spd": 46, "stage": 1, "nextForm": "Sandaconda", "evoTrigger": 8},
  {"id": 844, "name": "Sandaconda", "type": "Terra", "secondType": "", "BaseTotal": 327, "hp": 72, "atk": 86, "def": 98, "spd": 71, "stage": 2, "nextForm": null},
  {"id": 845, "name": "Cramorant", "type": "Voador", "secondType": "Água", "BaseTotal": 315, "hp": 70, "atk": 85, "def": 75, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 846, "name": "Arrokuda", "type": "Água", "secondType": "", "BaseTotal": 194, "hp": 41, "atk": 52, "def": 35, "spd": 66, "stage": 1, "nextForm": "Barraskewda", "evoTrigger": 8},
  {"id": 847, "name": "Barraskewda", "type": "Água", "secondType": "", "BaseTotal": 344, "hp": 61, "atk": 92, "def": 55, "spd": 136, "stage": 2, "nextForm": null},
  {"id": 848, "name": "Toxel", "type": "Elétrico", "secondType": "Veneno", "BaseTotal": 161, "hp": 40, "atk": 46, "def": 35, "spd": 40, "stage": 1, "nextForm": "Toxtricity", "evoTrigger": 8},
  {"id": 849, "name": "Toxtricity", "type": "Elétrico", "secondType": "Veneno", "BaseTotal": 326, "hp": 75, "atk": 106, "def": 70, "spd": 75, "stage": 2, "nextForm": null},
  {"id": 850, "name": "Sizzlipede", "type": "Fogo", "secondType": "Inseto", "BaseTotal": 201, "hp": 50, "atk": 58, "def": 48, "spd": 45, "stage": 1, "nextForm": "Centiskorch", "evoTrigger": 8},
  {"id": 851, "name": "Centiskorch", "type": "Fogo", "secondType": "Inseto", "BaseTotal": 345, "hp": 100, "atk": 102, "def": 78, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 852, "name": "Clobbopus", "type": "Lutador", "secondType": "", "BaseTotal": 196, "hp": 50, "atk": 59, "def": 55, "spd": 32, "stage": 1, "nextForm": "Grapploct", "evoTrigger": 8},
  {"id": 853, "name": "Grapploct", "type": "Lutador", "secondType": "", "BaseTotal": 301, "hp": 80, "atk": 94, "def": 85, "spd": 42, "stage": 2, "nextForm": null},
  {"id": 854, "name": "Sinistea", "type": "Fantasma", "secondType": "", "BaseTotal": 200, "hp": 40, "atk": 60, "def": 50, "spd": 50, "stage": 1, "nextForm": "Polteageist", "evoTrigger": 8},
  {"id": 855, "name": "Polteageist", "type": "Fantasma", "secondType": "", "BaseTotal": 320, "hp": 60, "atk": 100, "def": 90, "spd": 70, "stage": 2, "nextForm": null},
  {"id": 856, "name": "Hatenna", "type": "Psíquico", "secondType": "", "BaseTotal": 173, "hp": 42, "atk": 43, "def": 49, "spd": 39, "stage": 1, "nextForm": "Hattrem", "evoTrigger": 5},
  {"id": 857, "name": "Hattrem", "type": "Psíquico", "secondType": "", "BaseTotal": 238, "hp": 57, "atk": 63, "def": 69, "spd": 49, "stage": 2, "nextForm": "Hatterene", "evoTrigger": 10},
  {"id": 858, "name": "Hatterene", "type": "Psíquico", "secondType": "Fada", "BaseTotal": 298, "hp": 57, "atk": 113, "def": 99, "spd": 29, "stage": 3, "nextForm": null},
  {"id": 859, "name": "Impidimp", "type": "Noturno", "secondType": "Fada", "BaseTotal": 187, "hp": 45, "atk": 50, "def": 42, "spd": 50, "stage": 1, "nextForm": "Morgrem", "evoTrigger": 5},
  {"id": 860, "name": "Morgrem", "type": "Noturno", "secondType": "Fada", "BaseTotal": 261, "hp": 65, "atk": 68, "def": 58, "spd": 70, "stage": 2, "nextForm": "Grimmsnarl", "evoTrigger": 10},
  {"id": 861, "name": "Grimmsnarl", "type": "Noturno", "secondType": "Fada", "BaseTotal": 333, "hp": 95, "atk": 108, "def": 70, "spd": 60, "stage": 3, "nextForm": null},
  {"id": 862, "name": "Obstagoon", "type": "Noturno", "secondType": "Normal", "BaseTotal": 354, "hp": 93, "atk": 75, "def": 91, "spd": 95, "stage": 3, "nextForm": null},
  {"id": 863, "name": "Perrserker", "type": "Aço", "secondType": "", "BaseTotal": 280, "hp": 70, "atk": 80, "def": 80, "spd": 50, "stage": 2, "nextForm": null},
  {"id": 864, "name": "Cursola", "type": "Fantasma", "secondType": "", "BaseTotal": 300, "hp": 60, "atk": 120, "def": 90, "spd": 30, "stage": 1, "nextForm": null},
  {"id": 865, "name": "Sirfetch'd", "type": "Lutador", "secondType": "", "BaseTotal": 317, "hp": 62, "atk": 102, "def": 88, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 866, "name": "Mr. Rime", "type": "Gelo", "secondType": "Psíquico", "BaseTotal": 336, "hp": 80, "atk": 98, "def": 88, "spd": 70, "stage": 3, "nextForm": null},
  {"id": 867, "name": "Runerigus", "type": "Terra", "secondType": "Fantasma", "BaseTotal": 285, "hp": 58, "atk": 72, "def": 125, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 868, "name": "Milcery", "type": "Fada", "secondType": "", "BaseTotal": 174, "hp": 45, "atk": 45, "def": 50, "spd": 34, "stage": 1, "nextForm": "Alcremie", "evoTrigger": 8},
  {"id": 869, "name": "Alcremie", "type": "Fada", "secondType": "", "BaseTotal": 312, "hp": 65, "atk": 85, "def": 98, "spd": 64, "stage": 2, "nextForm": null},
  {"id": 870, "name": "Falinks", "type": "Lutador", "secondType": "", "BaseTotal": 305, "hp": 65, "atk": 85, "def": 80, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 871, "name": "Pincurchin", "type": "Elétrico", "secondType": "", "BaseTotal": 249, "hp": 48, "atk": 96, "def": 90, "spd": 15, "stage": 1, "nextForm": null},
  {"id": 872, "name": "Snom", "type": "Gelo", "secondType": "Inseto", "BaseTotal": 117, "hp": 30, "atk": 35, "def": 32, "spd": 20, "stage": 1, "nextForm": "Frosmoth", "evoTrigger": 8},
  {"id": 873, "name": "Frosmoth", "type": "Gelo", "secondType": "Inseto", "BaseTotal": 305, "hp": 70, "atk": 95, "def": 75, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 874, "name": "Stonjourner", "type": "Pedra", "secondType": "", "BaseTotal": 320, "hp": 100, "atk": 72, "def": 78, "spd": 70, "stage": 1, "nextForm": null},
  {"id": 875, "name": "Eiscue", "type": "Gelo", "secondType": "", "BaseTotal": 297, "hp": 75, "atk": 72, "def": 100, "spd": 50, "stage": 1, "nextForm": null},
  {"id": 876, "name": "Indeedee", "type": "Psíquico", "secondType": "Normal", "BaseTotal": 315, "hp": 60, "atk": 85, "def": 75, "spd": 95, "stage": 1, "nextForm": null},
  {"id": 877, "name": "Morpeko", "type": "Elétrico", "secondType": "Noturno", "BaseTotal": 295, "hp": 58, "atk": 82, "def": 58, "spd": 97, "stage": 1, "nextForm": null},
  {"id": 878, "name": "Cufant", "type": "Aço", "secondType": "", "BaseTotal": 221, "hp": 72, "atk": 60, "def": 49, "spd": 40, "stage": 1, "nextForm": "Copperajah", "evoTrigger": 8},
  {"id": 879, "name": "Copperajah", "type": "Aço", "secondType": "", "BaseTotal": 326, "hp": 122, "atk": 105, "def": 69, "spd": 30, "stage": 2, "nextForm": null},
  {"id": 880, "name": "Dracozolt", "type": "Elétrico", "secondType": "Dragão", "BaseTotal": 335, "hp": 90, "atk": 90, "def": 80, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 881, "name": "Arctozolt", "type": "Elétrico", "secondType": "Gelo", "BaseTotal": 325, "hp": 90, "atk": 95, "def": 85, "spd": 55, "stage": 1, "nextForm": null},
  {"id": 882, "name": "Dracovish", "type": "Água", "secondType": "Dragão", "BaseTotal": 335, "hp": 90, "atk": 80, "def": 90, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 883, "name": "Arctovish", "type": "Água", "secondType": "Gelo", "BaseTotal": 325, "hp": 90, "atk": 85, "def": 95, "spd": 55, "stage": 1, "nextForm": null},
  {"id": 884, "name": "Duraludon", "type": "Aço", "secondType": "Dragão", "BaseTotal": 345, "hp": 70, "atk": 108, "def": 82, "spd": 85, "stage": 1, "nextForm": null},
  {"id": 885, "name": "Dreepy", "type": "Dragão", "secondType": "Fantasma", "BaseTotal": 190, "hp": 28, "atk": 50, "def": 30, "spd": 82, "stage": 1, "nextForm": "Drakloak", "evoTrigger": 5},
  {"id": 886, "name": "Drakloak", "type": "Dragão", "secondType": "Fantasma", "BaseTotal": 290, "hp": 68, "atk": 70, "def": 50, "spd": 102, "stage": 2, "nextForm": "Dragapult", "evoTrigger": 10},
  {"id": 887, "name": "Dragapult", "type": "Dragão", "secondType": "Fantasma", "BaseTotal": 415, "hp": 88, "atk": 110, "def": 75, "spd": 142, "stage": 3, "nextForm": null},
  {"id": 888, "name": "Zacian", "type": "Fada", "secondType": "", "BaseTotal": 450, "hp": 92, "atk": 105, "def": 115, "spd": 138, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 889, "name": "Zamazenta", "type": "Lutador", "secondType": "", "BaseTotal": 450, "hp": 92, "atk": 105, "def": 115, "spd": 138, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 890, "name": "Eternatus", "type": "Veneno", "secondType": "Dragão", "BaseTotal": 480, "hp": 140, "atk": 115, "def": 95, "spd": 130, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 891, "name": "Kubfu", "type": "Lutador", "secondType": "", "BaseTotal": 259, "hp": 60, "atk": 72, "def": 55, "spd": 72, "stage": 1, "nextForm": "Urshifu", "evoTrigger": 8, "isLegendary": true},
  {"id": 892, "name": "Urshifu", "type": "Lutador", "secondType": "Noturno", "BaseTotal": 373, "hp": 100, "atk": 96, "def": 80, "spd": 97, "stage": 2, "nextForm": null, "isLegendary": true},
  {"id": 893, "name": "Zarude", "type": "Noturno", "secondType": "Grama", "BaseTotal": 405, "hp": 105, "atk": 95, "def": 100, "spd": 105, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 894, "name": "Regieleki", "type": "Elétrico", "secondType": "", "BaseTotal": 430, "hp": 80, "atk": 100, "def": 50, "spd": 200, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 895, "name": "Regidrago", "type": "Dragão", "secondType": "", "BaseTotal": 430, "hp": 200, "atk": 100, "def": 50, "spd": 80, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 896, "name": "Glastrier", "type": "Gelo", "secondType": "", "BaseTotal": 355, "hp": 100, "atk": 105, "def": 120, "spd": 30, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 897, "name": "Spectrier", "type": "Fantasma", "secondType": "", "BaseTotal": 405, "hp": 100, "atk": 105, "def": 70, "spd": 130, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 898, "name": "Calyrex", "type": "Psíquico", "secondType": "Grama", "BaseTotal": 340, "hp": 100, "atk": 80, "def": 80, "spd": 80, "stage": 1, "nextForm": null, "isLegendary": true}
];
