import type { PokemonData } from '../types';

export const GEN9: PokemonData[] = [
  {"id": 906, "name": "Sprigatito", "type": "Grama", "secondType": "", "BaseTotal": 208, "hp": 40, "atk": 53, "def": 50, "spd": 65, "stage": 1, "nextForm": "Floragato", "evoTrigger": 5},
  {"id": 907, "name": "Floragato", "type": "Grama", "secondType": "", "BaseTotal": 277, "hp": 61, "atk": 70, "def": 63, "spd": 83, "stage": 2, "nextForm": "Meowscarada", "evoTrigger": 10},
  {"id": 908, "name": "Meowscarada", "type": "Grama", "secondType": "Noturno", "BaseTotal": 365, "hp": 76, "atk": 96, "def": 70, "spd": 123, "stage": 3, "nextForm": null},
  {"id": 909, "name": "Fuecoco", "type": "Fogo", "secondType": "", "BaseTotal": 207, "hp": 67, "atk": 54, "def": 50, "spd": 36, "stage": 1, "nextForm": "Crocalor", "evoTrigger": 5},
  {"id": 910, "name": "Crocalor", "type": "Fogo", "secondType": "", "BaseTotal": 270, "hp": 81, "atk": 72, "def": 68, "spd": 49, "stage": 2, "nextForm": "Skeledirge", "evoTrigger": 10},
  {"id": 911, "name": "Skeledirge", "type": "Fogo", "secondType": "Fantasma", "BaseTotal": 350, "hp": 104, "atk": 92, "def": 88, "spd": 66, "stage": 3, "nextForm": null},
  {"id": 912, "name": "Quaxly", "type": "Água", "secondType": "", "BaseTotal": 208, "hp": 55, "atk": 58, "def": 45, "spd": 50, "stage": 1, "nextForm": "Quaxwell", "evoTrigger": 5},
  {"id": 913, "name": "Quaxwell", "type": "Água", "secondType": "", "BaseTotal": 272, "hp": 70, "atk": 75, "def": 62, "spd": 65, "stage": 2, "nextForm": "Quaquaval", "evoTrigger": 10},
  {"id": 914, "name": "Quaquaval", "type": "Água", "secondType": "Lutador", "BaseTotal": 350, "hp": 85, "atk": 102, "def": 78, "spd": 85, "stage": 3, "nextForm": null},
  {"id": 915, "name": "Lechonk", "type": "Normal", "secondType": "", "BaseTotal": 171, "hp": 54, "atk": 40, "def": 42, "spd": 35, "stage": 1, "nextForm": "Oinkologne", "evoTrigger": 8},
  {"id": 916, "name": "Oinkologne", "type": "Normal", "secondType": "", "BaseTotal": 333, "hp": 110, "atk": 80, "def": 78, "spd": 65, "stage": 2, "nextForm": null},
  {"id": 917, "name": "Tarountula", "type": "Inseto", "secondType": "", "BaseTotal": 132, "hp": 35, "atk": 35, "def": 42, "spd": 20, "stage": 1, "nextForm": "Spidops", "evoTrigger": 8},
  {"id": 918, "name": "Spidops", "type": "Inseto", "secondType": "", "BaseTotal": 250, "hp": 60, "atk": 66, "def": 89, "spd": 35, "stage": 2, "nextForm": null},
  {"id": 919, "name": "Nymble", "type": "Inseto", "secondType": "", "BaseTotal": 144, "hp": 33, "atk": 34, "def": 32, "spd": 45, "stage": 1, "nextForm": "Lokix", "evoTrigger": 8},
  {"id": 920, "name": "Lokix", "type": "Inseto", "secondType": "Noturno", "BaseTotal": 306, "hp": 71, "atk": 77, "def": 66, "spd": 92, "stage": 2, "nextForm": null},
  {"id": 921, "name": "Pawmi", "type": "Elétrico", "secondType": "", "BaseTotal": 172, "hp": 45, "atk": 45, "def": 22, "spd": 60, "stage": 1, "nextForm": "Pawmo", "evoTrigger": 5},
  {"id": 922, "name": "Pawmo", "type": "Elétrico", "secondType": "Lutador", "BaseTotal": 247, "hp": 60, "atk": 62, "def": 40, "spd": 85, "stage": 2, "nextForm": "Pawmot", "evoTrigger": 10},
  {"id": 923, "name": "Pawmot", "type": "Elétrico", "secondType": "Lutador", "BaseTotal": 332, "hp": 70, "atk": 92, "def": 65, "spd": 105, "stage": 3, "nextForm": null},
  {"id": 924, "name": "Tandemaus", "type": "Normal", "secondType": "", "BaseTotal": 215, "hp": 50, "atk": 45, "def": 45, "spd": 75, "stage": 1, "nextForm": "Maushold", "evoTrigger": 8},
  {"id": 925, "name": "Maushold", "type": "Normal", "secondType": "", "BaseTotal": 327, "hp": 74, "atk": 70, "def": 72, "spd": 111, "stage": 2, "nextForm": null},
  {"id": 926, "name": "Fidough", "type": "Fada", "secondType": "", "BaseTotal": 206, "hp": 37, "atk": 42, "def": 62, "spd": 65, "stage": 1, "nextForm": "Dachsbun", "evoTrigger": 8},
  {"id": 927, "name": "Dachsbun", "type": "Fada", "secondType": "", "BaseTotal": 315, "hp": 57, "atk": 65, "def": 98, "spd": 95, "stage": 2, "nextForm": null},
  {"id": 928, "name": "Smoliv", "type": "Grama", "secondType": "Normal", "BaseTotal": 165, "hp": 41, "atk": 46, "def": 48, "spd": 30, "stage": 1, "nextForm": "Dolliv", "evoTrigger": 5},
  {"id": 929, "name": "Dolliv", "type": "Grama", "secondType": "Normal", "BaseTotal": 220, "hp": 52, "atk": 66, "def": 69, "spd": 33, "stage": 2, "nextForm": "Arboliva", "evoTrigger": 10},
  {"id": 930, "name": "Arboliva", "type": "Grama", "secondType": "Normal", "BaseTotal": 314, "hp": 78, "atk": 97, "def": 100, "spd": 39, "stage": 3, "nextForm": null},
  {"id": 931, "name": "Squawkabilly", "type": "Normal", "secondType": "Voador", "BaseTotal": 295, "hp": 82, "atk": 70, "def": 51, "spd": 92, "stage": 1, "nextForm": null},
  {"id": 932, "name": "Nacli", "type": "Pedra", "secondType": "", "BaseTotal": 180, "hp": 55, "atk": 45, "def": 55, "spd": 25, "stage": 1, "nextForm": "Naclstack", "evoTrigger": 5},
  {"id": 933, "name": "Naclstack", "type": "Pedra", "secondType": "", "BaseTotal": 225, "hp": 60, "atk": 48, "def": 82, "spd": 35, "stage": 2, "nextForm": "Garganacl", "evoTrigger": 10},
  {"id": 934, "name": "Garganacl", "type": "Pedra", "secondType": "", "BaseTotal": 317, "hp": 100, "atk": 72, "def": 110, "spd": 35, "stage": 3, "nextForm": null},
  {"id": 935, "name": "Charcadet", "type": "Fogo", "secondType": "", "BaseTotal": 165, "hp": 40, "atk": 50, "def": 40, "spd": 35, "stage": 1, "nextForm": "Armarouge", "evoTrigger": 8},
  {"id": 936, "name": "Armarouge", "type": "Fogo", "secondType": "Psíquico", "BaseTotal": 342, "hp": 85, "atk": 92, "def": 90, "spd": 75, "stage": 2, "nextForm": null},
  {"id": 937, "name": "Ceruledge", "type": "Fogo", "secondType": "Fantasma", "BaseTotal": 342, "hp": 75, "atk": 92, "def": 90, "spd": 85, "stage": 2, "nextForm": null},
  {"id": 938, "name": "Tadbulb", "type": "Elétrico", "secondType": "", "BaseTotal": 189, "hp": 61, "atk": 45, "def": 38, "spd": 45, "stage": 1, "nextForm": "Bellibolt", "evoTrigger": 8},
  {"id": 939, "name": "Bellibolt", "type": "Elétrico", "secondType": "", "BaseTotal": 325, "hp": 109, "atk": 84, "def": 87, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 940, "name": "Wattrel", "type": "Elétrico", "secondType": "Voador", "BaseTotal": 196, "hp": 40, "atk": 48, "def": 38, "spd": 70, "stage": 1, "nextForm": "Kilowattrel", "evoTrigger": 8},
  {"id": 941, "name": "Kilowattrel", "type": "Elétrico", "secondType": "Voador", "BaseTotal": 343, "hp": 70, "atk": 88, "def": 60, "spd": 125, "stage": 2, "nextForm": null},
  {"id": 942, "name": "Maschiff", "type": "Noturno", "secondType": "", "BaseTotal": 226, "hp": 60, "atk": 59, "def": 56, "spd": 51, "stage": 1, "nextForm": "Mabosstiff", "evoTrigger": 8},
  {"id": 943, "name": "Mabosstiff", "type": "Noturno", "secondType": "", "BaseTotal": 335, "hp": 80, "atk": 90, "def": 80, "spd": 85, "stage": 2, "nextForm": null},
  {"id": 944, "name": "Shroodle", "type": "Veneno", "secondType": "Normal", "BaseTotal": 202, "hp": 40, "atk": 52, "def": 35, "spd": 75, "stage": 1, "nextForm": "Grafaiai", "evoTrigger": 8},
  {"id": 945, "name": "Grafaiai", "type": "Veneno", "secondType": "Normal", "BaseTotal": 329, "hp": 63, "atk": 88, "def": 68, "spd": 110, "stage": 2, "nextForm": null},
  {"id": 946, "name": "Bramblin", "type": "Grama", "secondType": "Fantasma", "BaseTotal": 187, "hp": 40, "atk": 55, "def": 32, "spd": 60, "stage": 1, "nextForm": "Brambleghast", "evoTrigger": 8},
  {"id": 947, "name": "Brambleghast", "type": "Grama", "secondType": "Fantasma", "BaseTotal": 313, "hp": 55, "atk": 98, "def": 70, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 948, "name": "Toedscool", "type": "Terra", "secondType": "Grama", "BaseTotal": 223, "hp": 40, "atk": 45, "def": 68, "spd": 70, "stage": 1, "nextForm": "Toedscruel", "evoTrigger": 8},
  {"id": 949, "name": "Toedscruel", "type": "Terra", "secondType": "Grama", "BaseTotal": 347, "hp": 80, "atk": 75, "def": 92, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 950, "name": "Klawf", "type": "Pedra", "secondType": "", "BaseTotal": 298, "hp": 70, "atk": 68, "def": 85, "spd": 75, "stage": 1, "nextForm": null},
  {"id": 951, "name": "Capsakid", "type": "Grama", "secondType": "", "BaseTotal": 202, "hp": 50, "atk": 62, "def": 40, "spd": 50, "stage": 1, "nextForm": "Scovillain", "evoTrigger": 8},
  {"id": 952, "name": "Scovillain", "type": "Grama", "secondType": "Fogo", "BaseTotal": 313, "hp": 65, "atk": 108, "def": 65, "spd": 75, "stage": 2, "nextForm": null},
  {"id": 953, "name": "Rellor", "type": "Inseto", "secondType": "", "BaseTotal": 170, "hp": 41, "atk": 40, "def": 59, "spd": 30, "stage": 1, "nextForm": "Rabsca", "evoTrigger": 8},
  {"id": 954, "name": "Rabsca", "type": "Inseto", "secondType": "Psíquico", "BaseTotal": 294, "hp": 75, "atk": 82, "def": 92, "spd": 45, "stage": 2, "nextForm": null},
  {"id": 955, "name": "Flittle", "type": "Psíquico", "secondType": "", "BaseTotal": 180, "hp": 30, "atk": 45, "def": 30, "spd": 75, "stage": 1, "nextForm": "Espathra", "evoTrigger": 8},
  {"id": 956, "name": "Espathra", "type": "Psíquico", "secondType": "", "BaseTotal": 340, "hp": 95, "atk": 80, "def": 60, "spd": 105, "stage": 2, "nextForm": null},
  {"id": 957, "name": "Tinkatink", "type": "Fada", "secondType": "Aço", "BaseTotal": 202, "hp": 50, "atk": 40, "def": 54, "spd": 58, "stage": 1, "nextForm": "Tinkatuff", "evoTrigger": 5},
  {"id": 958, "name": "Tinkatuff", "type": "Fada", "secondType": "Aço", "BaseTotal": 261, "hp": 65, "atk": 50, "def": 68, "spd": 78, "stage": 2, "nextForm": "Tinkaton", "evoTrigger": 10},
  {"id": 959, "name": "Tinkaton", "type": "Fada", "secondType": "Aço", "BaseTotal": 342, "hp": 85, "atk": 72, "def": 91, "spd": 94, "stage": 3, "nextForm": null},
  {"id": 960, "name": "Wiglett", "type": "Água", "secondType": "", "BaseTotal": 175, "hp": 10, "atk": 45, "def": 25, "spd": 95, "stage": 1, "nextForm": "Wugtrio", "evoTrigger": 8},
  {"id": 961, "name": "Wugtrio", "type": "Água", "secondType": "", "BaseTotal": 290, "hp": 35, "atk": 75, "def": 60, "spd": 120, "stage": 2, "nextForm": null},
  {"id": 962, "name": "Bombirdier", "type": "Voador", "secondType": "Noturno", "BaseTotal": 319, "hp": 70, "atk": 82, "def": 85, "spd": 82, "stage": 1, "nextForm": null},
  {"id": 963, "name": "Finizen", "type": "Água", "secondType": "", "BaseTotal": 230, "hp": 70, "atk": 45, "def": 40, "spd": 75, "stage": 1, "nextForm": "Palafin", "evoTrigger": 8},
  {"id": 964, "name": "Palafin", "type": "Água", "secondType": "", "BaseTotal": 329, "hp": 100, "atk": 62, "def": 67, "spd": 100, "stage": 2, "nextForm": null},
  {"id": 965, "name": "Varoom", "type": "Aço", "secondType": "Veneno", "BaseTotal": 196, "hp": 45, "atk": 50, "def": 54, "spd": 47, "stage": 1, "nextForm": "Revavroom", "evoTrigger": 8},
  {"id": 966, "name": "Revavroom", "type": "Aço", "secondType": "Veneno", "BaseTotal": 334, "hp": 80, "atk": 86, "def": 78, "spd": 90, "stage": 2, "nextForm": null},
  {"id": 967, "name": "Cyclizar", "type": "Dragão", "secondType": "Normal", "BaseTotal": 346, "hp": 70, "atk": 90, "def": 65, "spd": 121, "stage": 1, "nextForm": null},
  {"id": 968, "name": "Orthworm", "type": "Aço", "secondType": "", "BaseTotal": 307, "hp": 70, "atk": 72, "def": 100, "spd": 65, "stage": 1, "nextForm": null},
  {"id": 969, "name": "Glimmet", "type": "Pedra", "secondType": "Veneno", "BaseTotal": 229, "hp": 48, "atk": 70, "def": 51, "spd": 60, "stage": 1, "nextForm": "Glimmora", "evoTrigger": 8},
  {"id": 970, "name": "Glimmora", "type": "Pedra", "secondType": "Veneno", "BaseTotal": 347, "hp": 83, "atk": 92, "def": 86, "spd": 86, "stage": 2, "nextForm": null},
  {"id": 971, "name": "Greavard", "type": "Fantasma", "secondType": "", "BaseTotal": 188, "hp": 50, "atk": 46, "def": 58, "spd": 34, "stage": 1, "nextForm": "Houndstone", "evoTrigger": 8},
  {"id": 972, "name": "Houndstone", "type": "Fantasma", "secondType": "", "BaseTotal": 314, "hp": 72, "atk": 76, "def": 98, "spd": 68, "stage": 2, "nextForm": null},
  {"id": 973, "name": "Flamigo", "type": "Voador", "secondType": "Lutador", "BaseTotal": 336, "hp": 82, "atk": 95, "def": 69, "spd": 90, "stage": 1, "nextForm": null},
  {"id": 974, "name": "Cetoddle", "type": "Gelo", "secondType": "", "BaseTotal": 242, "hp": 108, "atk": 49, "def": 42, "spd": 43, "stage": 1, "nextForm": "Cetitan", "evoTrigger": 8},
  {"id": 975, "name": "Cetitan", "type": "Gelo", "secondType": "", "BaseTotal": 382, "hp": 170, "atk": 79, "def": 60, "spd": 73, "stage": 2, "nextForm": null},
  {"id": 976, "name": "Veluza", "type": "Água", "secondType": "Psíquico", "BaseTotal": 319, "hp": 90, "atk": 90, "def": 69, "spd": 70, "stage": 1, "nextForm": null},
  {"id": 977, "name": "Dondozo", "type": "Água", "secondType": "", "BaseTotal": 357, "hp": 150, "atk": 82, "def": 90, "spd": 35, "stage": 1, "nextForm": null},
  {"id": 978, "name": "Tatsugiri", "type": "Dragão", "secondType": "Água", "BaseTotal": 313, "hp": 68, "atk": 85, "def": 78, "spd": 82, "stage": 1, "nextForm": null},
  {"id": 979, "name": "Annihilape", "type": "Lutador", "secondType": "Fantasma", "BaseTotal": 367, "hp": 110, "atk": 82, "def": 85, "spd": 90, "stage": 3, "nextForm": null},
  {"id": 980, "name": "Clodsire", "type": "Veneno", "secondType": "Terra", "BaseTotal": 290, "hp": 130, "atk": 60, "def": 80, "spd": 20, "stage": 2, "nextForm": null},
  {"id": 981, "name": "Farigiraf", "type": "Normal", "secondType": "Psíquico", "BaseTotal": 350, "hp": 120, "atk": 100, "def": 70, "spd": 60, "stage": 2, "nextForm": null},
  {"id": 982, "name": "Dudunsparce", "type": "Normal", "secondType": "", "BaseTotal": 350, "hp": 125, "atk": 92, "def": 78, "spd": 55, "stage": 2, "nextForm": null},
  {"id": 983, "name": "Kingambit", "type": "Noturno", "secondType": "Aço", "BaseTotal": 350, "hp": 100, "atk": 98, "def": 102, "spd": 50, "stage": 3, "nextForm": null},
  {"id": 984, "name": "Great Tusk", "type": "Terra", "secondType": "Lutador", "BaseTotal": 386, "hp": 115, "atk": 92, "def": 92, "spd": 87, "stage": 3, "nextForm": null},
  {"id": 985, "name": "Scream Tail", "type": "Fada", "secondType": "Psíquico", "BaseTotal": 398, "hp": 115, "atk": 65, "def": 107, "spd": 111, "stage": 3, "nextForm": null},
  {"id": 986, "name": "Brute Bonnet", "type": "Grama", "secondType": "Noturno", "BaseTotal": 368, "hp": 111, "atk": 103, "def": 99, "spd": 55, "stage": 3, "nextForm": null},
  {"id": 987, "name": "Flutter Mane", "type": "Fada", "secondType": "Fantasma", "BaseTotal": 380, "hp": 55, "atk": 95, "def": 95, "spd": 135, "stage": 3, "nextForm": null},
  {"id": 988, "name": "Slither Wing", "type": "Inseto", "secondType": "Lutador", "BaseTotal": 368, "hp": 85, "atk": 110, "def": 92, "spd": 81, "stage": 3, "nextForm": null},
  {"id": 989, "name": "Sandy Shocks", "type": "Elétrico", "secondType": "Terra", "BaseTotal": 378, "hp": 85, "atk": 101, "def": 91, "spd": 101, "stage": 3, "nextForm": null},
  {"id": 990, "name": "Iron Treads", "type": "Terra", "secondType": "Aço", "BaseTotal": 383, "hp": 90, "atk": 92, "def": 95, "spd": 106, "stage": 3, "nextForm": null},
  {"id": 991, "name": "Iron Bundle", "type": "Gelo", "secondType": "Água", "BaseTotal": 381, "hp": 56, "atk": 102, "def": 87, "spd": 136, "stage": 3, "nextForm": null},
  {"id": 992, "name": "Iron Hands", "type": "Lutador", "secondType": "Elétrico", "BaseTotal": 387, "hp": 154, "atk": 95, "def": 88, "spd": 50, "stage": 3, "nextForm": null},
  {"id": 993, "name": "Iron Jugulis", "type": "Noturno", "secondType": "Voador", "BaseTotal": 386, "hp": 94, "atk": 101, "def": 83, "spd": 108, "stage": 3, "nextForm": null},
  {"id": 994, "name": "Iron Moth", "type": "Fogo", "secondType": "Veneno", "BaseTotal": 380, "hp": 80, "atk": 105, "def": 85, "spd": 110, "stage": 3, "nextForm": null},
  {"id": 995, "name": "Iron Thorns", "type": "Pedra", "secondType": "Elétrico", "BaseTotal": 371, "hp": 100, "atk": 102, "def": 97, "spd": 72, "stage": 3, "nextForm": null},
  {"id": 996, "name": "Frigibax", "type": "Dragão", "secondType": "Gelo", "BaseTotal": 220, "hp": 65, "atk": 55, "def": 45, "spd": 55, "stage": 1, "nextForm": "Arctibax", "evoTrigger": 5},
  {"id": 997, "name": "Arctibax", "type": "Dragão", "secondType": "Gelo", "BaseTotal": 288, "hp": 90, "atk": 70, "def": 66, "spd": 62, "stage": 2, "nextForm": "Baxcalibur", "evoTrigger": 10},
  {"id": 998, "name": "Baxcalibur", "type": "Dragão", "secondType": "Gelo", "BaseTotal": 401, "hp": 115, "atk": 110, "def": 89, "spd": 87, "stage": 3, "nextForm": null},
  {"id": 999, "name": "Gimmighoul", "type": "Fantasma", "secondType": "", "BaseTotal": 177, "hp": 45, "atk": 52, "def": 70, "spd": 10, "stage": 1, "nextForm": "Gholdengo", "evoTrigger": 8},
  {"id": 1000, "name": "Gholdengo", "type": "Aço", "secondType": "Fantasma", "BaseTotal": 360, "hp": 87, "atk": 96, "def": 93, "spd": 84, "stage": 2, "nextForm": null},
  {"id": 1001, "name": "Wo-Chien", "type": "Grama", "secondType": "Noturno", "BaseTotal": 363, "hp": 85, "atk": 90, "def": 118, "spd": 70, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 1002, "name": "Chien-Pao", "type": "Noturno", "secondType": "Gelo", "BaseTotal": 392, "hp": 80, "atk": 105, "def": 72, "spd": 135, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 1003, "name": "Ting-Lu", "type": "Terra", "secondType": "Noturno", "BaseTotal": 384, "hp": 155, "atk": 82, "def": 102, "spd": 45, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 1004, "name": "Chi-Yu", "type": "Noturno", "secondType": "Fogo", "BaseTotal": 363, "hp": 55, "atk": 108, "def": 100, "spd": 100, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 1005, "name": "Roaring Moon", "type": "Dragão", "secondType": "Noturno", "BaseTotal": 407, "hp": 105, "atk": 97, "def": 86, "spd": 119, "stage": 3, "nextForm": null, "isLegendary": true},
  {"id": 1006, "name": "Iron Valiant", "type": "Fada", "secondType": "Lutador", "BaseTotal": 390, "hp": 74, "atk": 125, "def": 75, "spd": 116, "stage": 3, "nextForm": null, "isLegendary": true},
  {"id": 1007, "name": "Koraidon", "type": "Lutador", "secondType": "Dragão", "BaseTotal": 453, "hp": 100, "atk": 110, "def": 108, "spd": 135, "stage": 1, "nextForm": null, "isLegendary": true},
  {"id": 1008, "name": "Miraidon", "type": "Elétrico", "secondType": "Dragão", "BaseTotal": 453, "hp": 100, "atk": 110, "def": 108, "spd": 135, "stage": 1, "nextForm": null, "isLegendary": true}
];
